-- SQLite schema for the SEC Form 13F data set.
--
-- Column names, declared Oracle-style types, nullability, and primary keys are
-- taken from FORM13F_readme.htm and FORM13F_metadata.json. OTHERMANAGER2 is the
-- one exception: the SEC metadata names ACCESSION_NUMBER alone as its key even
-- though the source contains multiple distinct rows per accession, including
-- repeated SEQUENCENUMBER values. No key is enforced on that table so every
-- source record is preserved without adding a non-SEC column.

CREATE TABLE SUBMISSION (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    FILING_DATE DATE NOT NULL,
    SUBMISSIONTYPE VARCHAR2(10) NOT NULL,
    CIK VARCHAR2(10) NOT NULL,
    PERIODOFREPORT DATE NOT NULL,
    PRIMARY KEY (ACCESSION_NUMBER)
);

CREATE TABLE COVERPAGE (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    REPORTCALENDARORQUARTER DATE NOT NULL,
    ISAMENDMENT CHAR(1),
    AMENDMENTNO NUMBER(2),
    AMENDMENTTYPE VARCHAR2(20),
    CONFDENIEDEXPIRED CHAR(1),
    DATEDENIEDEXPIRED DATE,
    DATEREPORTED DATE,
    REASONFORNONCONFIDENTIALITY VARCHAR2(40),
    FILINGMANAGER_NAME VARCHAR2(150) NOT NULL,
    FILINGMANAGER_STREET1 VARCHAR2(40),
    FILINGMANAGER_STREET2 VARCHAR2(40),
    FILINGMANAGER_CITY VARCHAR2(30),
    FILINGMANAGER_STATEORCOUNTRY CHAR(2),
    FILINGMANAGER_ZIPCODE VARCHAR2(10),
    REPORTTYPE VARCHAR2(30) NOT NULL,
    FORM13FFILENUMBER VARCHAR2(17),
    CRDNUMBER VARCHAR2(9),
    SECFILENUMBER VARCHAR2(17),
    PROVIDEINFOFORINSTRUCTION5 CHAR(1) NOT NULL,
    ADDITIONALINFORMATION VARCHAR2(4000),
    PRIMARY KEY (ACCESSION_NUMBER)
);

CREATE TABLE OTHERMANAGER (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    OTHERMANAGER_SK NUMBER(38) NOT NULL,
    CIK VARCHAR2(10),
    FORM13FFILENUMBER VARCHAR2(17),
    CRDNUMBER VARCHAR2(9),
    SECFILENUMBER VARCHAR2(17),
    NAME VARCHAR2(150) NOT NULL,
    PRIMARY KEY (ACCESSION_NUMBER, OTHERMANAGER_SK)
);

CREATE TABLE SIGNATURE (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    NAME VARCHAR2(150) NOT NULL,
    TITLE VARCHAR2(60) NOT NULL,
    PHONE VARCHAR2(20),
    SIGNATURE VARCHAR2(150) NOT NULL,
    CITY VARCHAR2(30) NOT NULL,
    STATEORCOUNTRY CHAR(2) NOT NULL,
    SIGNATUREDATE DATE NOT NULL,
    PRIMARY KEY (ACCESSION_NUMBER)
);

CREATE TABLE SUMMARYPAGE (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    OTHERINCLUDEDMANAGERSCOUNT NUMBER(3),
    TABLEENTRYTOTAL NUMBER(6),
    TABLEVALUETOTAL NUMBER(16),
    ISCONFIDENTIALOMITTED CHAR(1),
    PRIMARY KEY (ACCESSION_NUMBER)
);

CREATE TABLE OTHERMANAGER2 (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    SEQUENCENUMBER NUMBER(3) NOT NULL,
    CIK VARCHAR2(10),
    FORM13FFILENUMBER VARCHAR2(17),
    CRDNUMBER VARCHAR2(9),
    SECFILENUMBER VARCHAR2(17),
    NAME VARCHAR2(150) NOT NULL
);

CREATE TABLE INFOTABLE (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    INFOTABLE_SK NUMBER(38) NOT NULL,
    NAMEOFISSUER VARCHAR2(200) NOT NULL,
    TITLEOFCLASS VARCHAR2(150) NOT NULL,
    CUSIP CHAR(9) NOT NULL,
    FIGI VARCHAR2(12),
    VALUE NUMBER(16) NOT NULL,
    SSHPRNAMT NUMBER(16) NOT NULL,
    SSHPRNAMTTYPE VARCHAR2(10) NOT NULL,
    PUTCALL VARCHAR2(10),
    INVESTMENTDISCRETION VARCHAR2(10) NOT NULL,
    OTHERMANAGER VARCHAR2(100),
    VOTING_AUTH_SOLE NUMBER(16) NOT NULL,
    VOTING_AUTH_SHARED NUMBER(16) NOT NULL,
    VOTING_AUTH_NONE NUMBER(16) NOT NULL,
    PRIMARY KEY (ACCESSION_NUMBER, INFOTABLE_SK)
);

-- Import provenance. Raw SEC tables remain unchanged; accession membership is
-- recorded in a bridge table instead of adding non-SEC columns to them.
CREATE TABLE ETL_BATCH (
    ETL_BATCH_ID INTEGER PRIMARY KEY,
    DATASET_QUARTER VARCHAR(6),
    ZIP_FILENAME TEXT NOT NULL,
    ZIP_SHA256 CHAR(64) NOT NULL UNIQUE,
    SOURCE_PATH TEXT NOT NULL,
    IMPORT_MODE TEXT NOT NULL
        CHECK (IMPORT_MODE IN ('APPEND', 'REGISTER_EXISTING')),
    STATUS TEXT NOT NULL
        CHECK (STATUS IN ('RUNNING', 'COMPLETED', 'FAILED')),
    STARTED_AT TEXT NOT NULL,
    COMPLETED_AT TEXT,
    ERROR_MESSAGE TEXT
);

CREATE TABLE ETL_BATCH_TABLE_COUNT (
    ETL_BATCH_ID INTEGER NOT NULL,
    TABLE_NAME TEXT NOT NULL,
    SOURCE_ROW_COUNT INTEGER NOT NULL,
    DATABASE_ROW_COUNT INTEGER,
    PRIMARY KEY (ETL_BATCH_ID, TABLE_NAME),
    FOREIGN KEY (ETL_BATCH_ID)
        REFERENCES ETL_BATCH (ETL_BATCH_ID) ON DELETE CASCADE
);

CREATE TABLE ETL_BATCH_ACCESSION (
    ETL_BATCH_ID INTEGER NOT NULL,
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    PRIMARY KEY (ETL_BATCH_ID, ACCESSION_NUMBER),
    UNIQUE (ACCESSION_NUMBER),
    FOREIGN KEY (ETL_BATCH_ID)
        REFERENCES ETL_BATCH (ETL_BATCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (ACCESSION_NUMBER)
        REFERENCES SUBMISSION (ACCESSION_NUMBER)
);

-- CIK dimension populated by etl/enrich_cik.py. TICKER and EXCHANGE are ordered,
-- comma-separated lists for convenient browsing; CIK_TICKER_EXCHANGE preserves
-- each ticker/exchange pair as a normalized row.
CREATE TABLE CIK (
    CIK CHAR(10) NOT NULL,
    SEC_COMPANY_NAME VARCHAR2(200),
    MANAGER_NAME VARCHAR2(150),
    TICKER TEXT,
    EXCHANGE TEXT,
    FILINGMANAGER_STREET1 VARCHAR2(40),
    FILINGMANAGER_STREET2 VARCHAR2(40),
    FILINGMANAGER_CITY VARCHAR2(30),
    FILINGMANAGER_STATEORCOUNTRY CHAR(2),
    FILINGMANAGER_ZIPCODE VARCHAR2(10),
    FORM13FFILENUMBER VARCHAR2(17),
    CRDNUMBER VARCHAR2(9),
    SECFILENUMBER VARCHAR2(17),
    LATEST_RELATED_ACCESSION_NUMBER VARCHAR2(25),
    LATEST_FILING_DATE DATE,
    LATEST_PERIOD_OF_REPORT DATE,
    SUBMISSION_COUNT NUMBER(10) NOT NULL DEFAULT 0,
    OTHER_MANAGER_MENTION_COUNT NUMBER(10) NOT NULL DEFAULT 0,
    PRIMARY KEY (CIK)
);

CREATE TABLE CIK_TICKER_EXCHANGE (
    CIK CHAR(10) NOT NULL,
    SEC_COMPANY_NAME VARCHAR2(200) NOT NULL,
    TICKER VARCHAR2(32) NOT NULL,
    EXCHANGE VARCHAR2(32),
    SIC CHAR(4),
    SIC_DESCRIPTION TEXT,
    SIC_MAJOR_GROUP_DIVISION TEXT,
    SIC_AS_OF_DATE DATE,
    SIC_SOURCE TEXT,
    PRIMARY KEY (CIK, TICKER),
    FOREIGN KEY (CIK) REFERENCES CIK (CIK)
);

CREATE INDEX CIK_TICKER_EXCHANGE_TICKER_IDX
    ON CIK_TICKER_EXCHANGE (TICKER);

CREATE VIEW CIK_13F_RELATIONSHIP AS
SELECT printf('%010d', CAST(CIK AS INTEGER)) AS CIK,
       ACCESSION_NUMBER,
       'FILING_MANAGER' AS RELATIONSHIP_TYPE
FROM SUBMISSION
UNION ALL
SELECT printf('%010d', CAST(CIK AS INTEGER)) AS CIK,
       ACCESSION_NUMBER,
       'OTHER_MANAGER' AS RELATIONSHIP_TYPE
FROM OTHERMANAGER
WHERE CIK IS NOT NULL AND CIK <> ''
UNION ALL
SELECT printf('%010d', CAST(CIK AS INTEGER)) AS CIK,
       ACCESSION_NUMBER,
       'INCLUDED_OTHER_MANAGER' AS RELATIONSHIP_TYPE
FROM OTHERMANAGER2
WHERE CIK IS NOT NULL AND CIK <> '';

-- Stable CUSIP dimension and quarter-specific identity history populated by
-- etl/enrich_cusip.py. Integer surrogate keys remain stable across refreshes.
CREATE TABLE CUSIP (
    CUSIP_ID INTEGER PRIMARY KEY,
    CUSIP CHAR(9) NOT NULL UNIQUE
);

CREATE TABLE CUSIP_VARIANT (
    CUSIP_VARIANT_ID INTEGER PRIMARY KEY,
    CUSIP_ID INTEGER NOT NULL,
    REPORTCALENDARORQUARTER DATE NOT NULL,
    NAMEOFISSUER VARCHAR2(200) NOT NULL,
    TITLEOFCLASS VARCHAR2(150) NOT NULL,
    FIGI VARCHAR2(12),
    OCCURRENCE_COUNT NUMBER(16) NOT NULL,
    FOREIGN KEY (CUSIP_ID) REFERENCES CUSIP (CUSIP_ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX CUSIP_VARIANT_UQ
    ON CUSIP_VARIANT (
        CUSIP_ID,
        REPORTCALENDARORQUARTER,
        NAMEOFISSUER,
        TITLEOFCLASS,
        COALESCE(FIGI, '')
    );

CREATE INDEX CUSIP_VARIANT_CUSIP_ID_IDX ON CUSIP_VARIANT (CUSIP_ID);

CREATE INDEX INFOTABLE_CUSIP_IDX ON INFOTABLE (CUSIP);

CREATE VIEW CUSIP_CURRENT_VARIANT AS
WITH RANKED AS (
    SELECT
        D.CUSIP_ID,
        V.CUSIP_VARIANT_ID,
        D.CUSIP,
        V.REPORTCALENDARORQUARTER,
        V.NAMEOFISSUER,
        V.TITLEOFCLASS,
        V.FIGI,
        V.OCCURRENCE_COUNT,
        ROW_NUMBER() OVER (
            PARTITION BY D.CUSIP_ID
            ORDER BY
                substr(V.REPORTCALENDARORQUARTER, 8, 4) DESC,
                CASE substr(V.REPORTCALENDARORQUARTER, 4, 3)
                    WHEN 'DEC' THEN 12 WHEN 'SEP' THEN 9
                    WHEN 'JUN' THEN 6 WHEN 'MAR' THEN 3 ELSE 0
                END DESC,
                substr(V.REPORTCALENDARORQUARTER, 1, 2) DESC,
                V.OCCURRENCE_COUNT DESC,
                V.NAMEOFISSUER,
                V.TITLEOFCLASS,
                COALESCE(V.FIGI, ''),
                V.CUSIP_VARIANT_ID
        ) AS RN
    FROM CUSIP D
    JOIN CUSIP_VARIANT V USING (CUSIP_ID)
)
SELECT
    CUSIP_ID,
    CUSIP_VARIANT_ID AS CURRENT_CUSIP_VARIANT_ID,
    CUSIP,
    NAMEOFISSUER AS CURRENT_NAMEOFISSUER,
    TITLEOFCLASS AS CURRENT_TITLEOFCLASS,
    FIGI AS CURRENT_FIGI,
    REPORTCALENDARORQUARTER,
    OCCURRENCE_COUNT
FROM RANKED
WHERE RN = 1;

CREATE VIEW CUSIP_13F_HOLDING AS
SELECT
    D.CUSIP_ID,
    V.CUSIP_VARIANT_ID,
    I.CUSIP,
    I.ACCESSION_NUMBER,
    I.INFOTABLE_SK,
    printf('%010d', CAST(S.CIK AS INTEGER)) AS FILING_MANAGER_CIK,
    COALESCE(C.MANAGER_NAME, P.FILINGMANAGER_NAME) AS FILING_MANAGER_NAME,
    S.FILING_DATE,
    S.SUBMISSIONTYPE,
    S.PERIODOFREPORT,
    P.REPORTTYPE,
    P.FORM13FFILENUMBER,
    I.NAMEOFISSUER,
    I.TITLEOFCLASS,
    I.FIGI,
    I.VALUE,
    I.SSHPRNAMT,
    I.SSHPRNAMTTYPE,
    I.PUTCALL,
    I.INVESTMENTDISCRETION,
    I.OTHERMANAGER,
    I.VOTING_AUTH_SOLE,
    I.VOTING_AUTH_SHARED,
    I.VOTING_AUTH_NONE
FROM INFOTABLE I
JOIN SUBMISSION S USING (ACCESSION_NUMBER)
LEFT JOIN COVERPAGE P USING (ACCESSION_NUMBER)
JOIN CUSIP D ON D.CUSIP = I.CUSIP
LEFT JOIN CUSIP_VARIANT V
    ON V.CUSIP_ID = D.CUSIP_ID
   AND V.REPORTCALENDARORQUARTER = P.REPORTCALENDARORQUARTER
   AND V.NAMEOFISSUER = I.NAMEOFISSUER
   AND V.TITLEOFCLASS = I.TITLEOFCLASS
   AND V.FIGI IS I.FIGI
LEFT JOIN CIK C
    ON C.CIK = printf('%010d', CAST(S.CIK AS INTEGER));

-- Normalized dates and amendment-resolved filing components populated by
-- etl/build_canonical_filings.py.
CREATE TABLE QUARTER (
    QUARTER_ID INTEGER PRIMARY KEY,
    QUARTER_LABEL CHAR(6) NOT NULL UNIQUE,
    QUARTER_END_DATE DATE NOT NULL UNIQUE,
    YEAR INTEGER NOT NULL,
    QUARTER_NUMBER INTEGER NOT NULL CHECK (QUARTER_NUMBER BETWEEN 1 AND 4),
    PREVIOUS_QUARTER_ID INTEGER,
    FOREIGN KEY (PREVIOUS_QUARTER_ID) REFERENCES QUARTER (QUARTER_ID)
);

CREATE TABLE NORMALIZED_FILING (
    ACCESSION_NUMBER VARCHAR2(25) PRIMARY KEY,
    ETL_BATCH_ID INTEGER,
    MANAGER_CIK CHAR(10) NOT NULL,
    FILING_DATE_ISO DATE NOT NULL,
    PERIOD_OF_REPORT_ISO DATE NOT NULL,
    REPORT_CALENDAR_OR_QUARTER_ISO DATE,
    QUARTER_ID INTEGER,
    SUBMISSION_TYPE VARCHAR2(10) NOT NULL,
    REPORT_TYPE VARCHAR2(30),
    IS_AMENDMENT INTEGER NOT NULL CHECK (IS_AMENDMENT IN (0, 1)),
    AMENDMENT_NUMBER INTEGER,
    AMENDMENT_TYPE VARCHAR2(20),
    IS_CONFIDENTIAL_OMITTED INTEGER NOT NULL
        CHECK (IS_CONFIDENTIAL_OMITTED IN (0, 1)),
    FORM13F_FILE_NUMBER VARCHAR2(17),
    HAS_INFORMATION_TABLE INTEGER NOT NULL
        CHECK (HAS_INFORMATION_TABLE IN (0, 1)),
    FOREIGN KEY (ACCESSION_NUMBER)
        REFERENCES SUBMISSION (ACCESSION_NUMBER),
    FOREIGN KEY (ETL_BATCH_ID) REFERENCES ETL_BATCH (ETL_BATCH_ID),
    FOREIGN KEY (QUARTER_ID) REFERENCES QUARTER (QUARTER_ID)
);

CREATE INDEX NORMALIZED_FILING_MANAGER_QUARTER_IDX
    ON NORMALIZED_FILING (MANAGER_CIK, QUARTER_ID);

CREATE INDEX NORMALIZED_FILING_BATCH_IDX
    ON NORMALIZED_FILING (ETL_BATCH_ID);

CREATE TABLE FILING_OVERRIDE (
    ACCESSION_NUMBER VARCHAR2(25) PRIMARY KEY,
    OVERRIDE_COMPONENT_TYPE TEXT NOT NULL
        CHECK (
            OVERRIDE_COMPONENT_TYPE IN (
                'BASE', 'RESTATEMENT', 'ADDITION', 'EXCLUDE'
            )
        ),
    REASON TEXT NOT NULL,
    REVIEWED_AT TEXT NOT NULL,
    FOREIGN KEY (ACCESSION_NUMBER)
        REFERENCES SUBMISSION (ACCESSION_NUMBER)
);

CREATE TABLE CANONICAL_FILING (
    CANONICAL_FILING_ID INTEGER PRIMARY KEY,
    MANAGER_CIK CHAR(10) NOT NULL,
    QUARTER_ID INTEGER NOT NULL,
    RESOLUTION_STATUS TEXT NOT NULL
        CHECK (
            RESOLUTION_STATUS IN (
                'RESOLVED', 'REVIEW_REQUIRED', 'INCOMPLETE_HISTORY'
            )
        ),
    IS_ANALYTICS_READY INTEGER NOT NULL
        CHECK (IS_ANALYTICS_READY IN (0, 1)),
    HAS_AMENDMENT INTEGER NOT NULL CHECK (HAS_AMENDMENT IN (0, 1)),
    HAS_CONFIDENTIAL_OMISSION INTEGER NOT NULL
        CHECK (HAS_CONFIDENTIAL_OMISSION IN (0, 1)),
    EFFECTIVE_COMPONENT_COUNT INTEGER NOT NULL,
    LATEST_ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    BUILT_AT TEXT NOT NULL,
    UNIQUE (MANAGER_CIK, QUARTER_ID),
    FOREIGN KEY (QUARTER_ID) REFERENCES QUARTER (QUARTER_ID),
    FOREIGN KEY (LATEST_ACCESSION_NUMBER)
        REFERENCES SUBMISSION (ACCESSION_NUMBER)
);

CREATE TABLE CANONICAL_FILING_COMPONENT (
    ACCESSION_NUMBER VARCHAR2(25) PRIMARY KEY,
    CANONICAL_FILING_ID INTEGER NOT NULL,
    COMPONENT_TYPE TEXT NOT NULL
        CHECK (
            COMPONENT_TYPE IN (
                'BASE', 'RESTATEMENT', 'ADDITION', 'UNKNOWN', 'EXCLUDE'
            )
        ),
    COMPONENT_SEQUENCE INTEGER NOT NULL,
    IS_EFFECTIVE INTEGER NOT NULL CHECK (IS_EFFECTIVE IN (0, 1)),
    SUPERSEDED_BY_ACCESSION_NUMBER VARCHAR2(25),
    FOREIGN KEY (ACCESSION_NUMBER)
        REFERENCES SUBMISSION (ACCESSION_NUMBER),
    FOREIGN KEY (CANONICAL_FILING_ID)
        REFERENCES CANONICAL_FILING (CANONICAL_FILING_ID) ON DELETE CASCADE,
    FOREIGN KEY (SUPERSEDED_BY_ACCESSION_NUMBER)
        REFERENCES SUBMISSION (ACCESSION_NUMBER)
);

CREATE INDEX CANONICAL_COMPONENT_FILING_IDX
    ON CANONICAL_FILING_COMPONENT (CANONICAL_FILING_ID, IS_EFFECTIVE);

CREATE VIEW FILING_VALUE_RECONCILIATION AS
WITH HOLDING_TOTAL AS (
    SELECT
        C.ACCESSION_NUMBER,
        SUM(I.VALUE) AS HOLDING_RAW_TOTAL,
        COUNT(*) AS HOLDING_ROW_COUNT
    FROM CANONICAL_FILING_COMPONENT C
    JOIN INFOTABLE I USING (ACCESSION_NUMBER)
    WHERE C.IS_EFFECTIVE = 1
    GROUP BY C.ACCESSION_NUMBER
)
SELECT
    H.ACCESSION_NUMBER,
    H.HOLDING_ROW_COUNT,
    H.HOLDING_RAW_TOTAL,
    S.TABLEVALUETOTAL AS SUMMARY_RAW_TOTAL,
    H.HOLDING_RAW_TOTAL - S.TABLEVALUETOTAL AS RAW_DIFFERENCE,
    CASE
        WHEN S.TABLEVALUETOTAL IS NULL THEN 'NO_SUMMARY'
        WHEN H.HOLDING_RAW_TOTAL = S.TABLEVALUETOTAL THEN 'MATCH'
        WHEN ABS(H.HOLDING_RAW_TOTAL - S.TABLEVALUETOTAL) <= 1
            THEN 'ROUNDING_DIFFERENCE'
        WHEN S.TABLEVALUETOTAL = 0 THEN 'SUMMARY_ZERO'
        WHEN H.HOLDING_RAW_TOTAL
             BETWEEN S.TABLEVALUETOTAL * 999
                 AND S.TABLEVALUETOTAL * 1001
            THEN 'HOLDINGS_APPROX_1000X_SUMMARY'
        WHEN S.TABLEVALUETOTAL
             BETWEEN H.HOLDING_RAW_TOTAL * 999
                 AND H.HOLDING_RAW_TOTAL * 1001
            THEN 'SUMMARY_APPROX_1000X_HOLDINGS'
        ELSE 'MISMATCH'
    END AS RECONCILIATION_STATUS
FROM HOLDING_TOTAL H
LEFT JOIN SUMMARYPAGE S USING (ACCESSION_NUMBER);

CREATE VIEW CANONICAL_HOLDING_LINE AS
SELECT
    F.CANONICAL_FILING_ID,
    F.MANAGER_CIK,
    F.QUARTER_ID,
    Q.QUARTER_LABEL,
    Q.QUARTER_END_DATE,
    F.RESOLUTION_STATUS,
    F.IS_ANALYTICS_READY,
    F.HAS_CONFIDENTIAL_OMISSION,
    C.ACCESSION_NUMBER,
    R.RECONCILIATION_STATUS AS VALUE_RECONCILIATION_STATUS,
    I.INFOTABLE_SK,
    D.CUSIP_ID,
    I.CUSIP,
    I.NAMEOFISSUER,
    I.TITLEOFCLASS,
    I.FIGI,
    I.VALUE AS RAW_REPORTED_VALUE,
    CASE
        WHEN N.FILING_DATE_ISO < '2023-01-03' THEN 1000
        ELSE 1
    END AS VALUE_MULTIPLIER,
    I.VALUE * CASE
        WHEN N.FILING_DATE_ISO < '2023-01-03' THEN 1000
        ELSE 1
    END AS VALUE_USD,
    I.SSHPRNAMT,
    I.SSHPRNAMTTYPE,
    I.PUTCALL,
    I.INVESTMENTDISCRETION,
    I.OTHERMANAGER,
    I.VOTING_AUTH_SOLE,
    I.VOTING_AUTH_SHARED,
    I.VOTING_AUTH_NONE
FROM CANONICAL_FILING F
JOIN QUARTER Q USING (QUARTER_ID)
JOIN CANONICAL_FILING_COMPONENT C
    ON C.CANONICAL_FILING_ID = F.CANONICAL_FILING_ID
   AND C.IS_EFFECTIVE = 1
JOIN NORMALIZED_FILING N USING (ACCESSION_NUMBER)
JOIN INFOTABLE I USING (ACCESSION_NUMBER)
LEFT JOIN FILING_VALUE_RECONCILIATION R USING (ACCESSION_NUMBER)
LEFT JOIN CUSIP D ON D.CUSIP = I.CUSIP;

CREATE VIEW ANALYTICS_HOLDING_LINE AS
SELECT *
FROM CANONICAL_HOLDING_LINE
WHERE IS_ANALYTICS_READY = 1;
