-- SQLite schema for the SEC Form 13F data set.
--
-- Column names, declared Oracle-style types, nullability, and primary keys are
-- taken from FORM13F_readme.htm and FORM13F_metadata.json. OTHERMANAGER2 is the
-- one exception: the SEC metadata names ACCESSION_NUMBER alone as its key even
-- though the source contains multiple distinct rows per accession, including
-- repeated SEQUENCENUMBER values. No key is enforced on that table so every
-- source record is preserved without adding a non-SEC column.

CREATE TABLE SUBMISSION (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    FILING_DATE DATE NOT NULL,
    SUBMISSIONTYPE VARCHAR2(10) NOT NULL,
    CIK VARCHAR2(10) NOT NULL,
    PERIODOFREPORT DATE NOT NULL,
    PRIMARY KEY (ACCESSION_NUMBER)
);

CREATE TABLE COVERPAGE (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    REPORTCALENDARORQUARTER DATE NOT NULL,
    ISAMENDMENT CHAR(1),
    AMENDMENTNO NUMBER(2),
    AMENDMENTTYPE VARCHAR2(20),
    CONFDENIEDEXPIRED CHAR(1),
    DATEDENIEDEXPIRED DATE,
    DATEREPORTED DATE,
    REASONFORNONCONFIDENTIALITY VARCHAR2(40),
    FILINGMANAGER_NAME VARCHAR2(150) NOT NULL,
    FILINGMANAGER_STREET1 VARCHAR2(40),
    FILINGMANAGER_STREET2 VARCHAR2(40),
    FILINGMANAGER_CITY VARCHAR2(30),
    FILINGMANAGER_STATEORCOUNTRY CHAR(2),
    FILINGMANAGER_ZIPCODE VARCHAR2(10),
    REPORTTYPE VARCHAR2(30) NOT NULL,
    FORM13FFILENUMBER VARCHAR2(17),
    CRDNUMBER VARCHAR2(9),
    SECFILENUMBER VARCHAR2(17),
    PROVIDEINFOFORINSTRUCTION5 CHAR(1) NOT NULL,
    ADDITIONALINFORMATION VARCHAR2(4000),
    PRIMARY KEY (ACCESSION_NUMBER)
);

CREATE TABLE OTHERMANAGER (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    OTHERMANAGER_SK NUMBER(38) NOT NULL,
    CIK VARCHAR2(10),
    FORM13FFILENUMBER VARCHAR2(17),
    CRDNUMBER VARCHAR2(9),
    SECFILENUMBER VARCHAR2(17),
    NAME VARCHAR2(150) NOT NULL,
    PRIMARY KEY (ACCESSION_NUMBER, OTHERMANAGER_SK)
);

CREATE TABLE SIGNATURE (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    NAME VARCHAR2(150) NOT NULL,
    TITLE VARCHAR2(60) NOT NULL,
    PHONE VARCHAR2(20),
    SIGNATURE VARCHAR2(150) NOT NULL,
    CITY VARCHAR2(30) NOT NULL,
    STATEORCOUNTRY CHAR(2) NOT NULL,
    SIGNATUREDATE DATE NOT NULL,
    PRIMARY KEY (ACCESSION_NUMBER)
);

CREATE TABLE SUMMARYPAGE (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    OTHERINCLUDEDMANAGERSCOUNT NUMBER(3),
    TABLEENTRYTOTAL NUMBER(6),
    TABLEVALUETOTAL NUMBER(16),
    ISCONFIDENTIALOMITTED CHAR(1),
    PRIMARY KEY (ACCESSION_NUMBER)
);

CREATE TABLE OTHERMANAGER2 (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    SEQUENCENUMBER NUMBER(3) NOT NULL,
    CIK VARCHAR2(10),
    FORM13FFILENUMBER VARCHAR2(17),
    CRDNUMBER VARCHAR2(9),
    SECFILENUMBER VARCHAR2(17),
    NAME VARCHAR2(150) NOT NULL
);

CREATE TABLE INFOTABLE (
    ACCESSION_NUMBER VARCHAR2(25) NOT NULL,
    INFOTABLE_SK NUMBER(38) NOT NULL,
    NAMEOFISSUER VARCHAR2(200) NOT NULL,
    TITLEOFCLASS VARCHAR2(150) NOT NULL,
    CUSIP CHAR(9) NOT NULL,
    FIGI VARCHAR2(12),
    VALUE NUMBER(16) NOT NULL,
    SSHPRNAMT NUMBER(16) NOT NULL,
    SSHPRNAMTTYPE VARCHAR2(10) NOT NULL,
    PUTCALL VARCHAR2(10),
    INVESTMENTDISCRETION VARCHAR2(10) NOT NULL,
    OTHERMANAGER VARCHAR2(100),
    VOTING_AUTH_SOLE NUMBER(16) NOT NULL,
    VOTING_AUTH_SHARED NUMBER(16) NOT NULL,
    VOTING_AUTH_NONE NUMBER(16) NOT NULL,
    PRIMARY KEY (ACCESSION_NUMBER, INFOTABLE_SK)
);

-- CIK dimension populated by etl/enrich_cik.py. TICKER and EXCHANGE are ordered,
-- comma-separated lists for convenient browsing; CIK_TICKER_EXCHANGE preserves
-- each ticker/exchange pair as a normalized row.
CREATE TABLE CIK (
    CIK CHAR(10) NOT NULL,
    SEC_COMPANY_NAME VARCHAR2(200),
    MANAGER_NAME VARCHAR2(150),
    TICKER TEXT,
    EXCHANGE TEXT,
    FILINGMANAGER_STREET1 VARCHAR2(40),
    FILINGMANAGER_STREET2 VARCHAR2(40),
    FILINGMANAGER_CITY VARCHAR2(30),
    FILINGMANAGER_STATEORCOUNTRY CHAR(2),
    FILINGMANAGER_ZIPCODE VARCHAR2(10),
    FORM13FFILENUMBER VARCHAR2(17),
    CRDNUMBER VARCHAR2(9),
    SECFILENUMBER VARCHAR2(17),
    LATEST_RELATED_ACCESSION_NUMBER VARCHAR2(25),
    LATEST_FILING_DATE DATE,
    LATEST_PERIOD_OF_REPORT DATE,
    SUBMISSION_COUNT NUMBER(10) NOT NULL DEFAULT 0,
    OTHER_MANAGER_MENTION_COUNT NUMBER(10) NOT NULL DEFAULT 0,
    PRIMARY KEY (CIK)
);

CREATE TABLE CIK_TICKER_EXCHANGE (
    CIK CHAR(10) NOT NULL,
    SEC_COMPANY_NAME VARCHAR2(200) NOT NULL,
    TICKER VARCHAR2(32) NOT NULL,
    EXCHANGE VARCHAR2(32),
    SIC CHAR(4),
    SIC_DESCRIPTION TEXT,
    SIC_MAJOR_GROUP_DIVISION TEXT,
    SIC_AS_OF_DATE DATE,
    SIC_SOURCE TEXT,
    PRIMARY KEY (CIK, TICKER),
    FOREIGN KEY (CIK) REFERENCES CIK (CIK)
);

CREATE INDEX CIK_TICKER_EXCHANGE_TICKER_IDX
    ON CIK_TICKER_EXCHANGE (TICKER);

CREATE VIEW CIK_13F_RELATIONSHIP AS
SELECT printf('%010d', CAST(CIK AS INTEGER)) AS CIK,
       ACCESSION_NUMBER,
       'FILING_MANAGER' AS RELATIONSHIP_TYPE
FROM SUBMISSION
UNION ALL
SELECT printf('%010d', CAST(CIK AS INTEGER)) AS CIK,
       ACCESSION_NUMBER,
       'OTHER_MANAGER' AS RELATIONSHIP_TYPE
FROM OTHERMANAGER
WHERE CIK IS NOT NULL AND CIK <> ''
UNION ALL
SELECT printf('%010d', CAST(CIK AS INTEGER)) AS CIK,
       ACCESSION_NUMBER,
       'INCLUDED_OTHER_MANAGER' AS RELATIONSHIP_TYPE
FROM OTHERMANAGER2
WHERE CIK IS NOT NULL AND CIK <> '';

-- Stable CUSIP dimension and quarter-specific identity history populated by
-- etl/enrich_cusip.py. Integer surrogate keys remain stable across refreshes.
CREATE TABLE CUSIP (
    CUSIP_ID INTEGER PRIMARY KEY,
    CUSIP CHAR(9) NOT NULL UNIQUE
);

CREATE TABLE CUSIP_VARIANT (
    CUSIP_VARIANT_ID INTEGER PRIMARY KEY,
    CUSIP_ID INTEGER NOT NULL,
    REPORTCALENDARORQUARTER DATE NOT NULL,
    NAMEOFISSUER VARCHAR2(200) NOT NULL,
    TITLEOFCLASS VARCHAR2(150) NOT NULL,
    FIGI VARCHAR2(12),
    OCCURRENCE_COUNT NUMBER(16) NOT NULL,
    FOREIGN KEY (CUSIP_ID) REFERENCES CUSIP (CUSIP_ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX CUSIP_VARIANT_UQ
    ON CUSIP_VARIANT (
        CUSIP_ID,
        REPORTCALENDARORQUARTER,
        NAMEOFISSUER,
        TITLEOFCLASS,
        COALESCE(FIGI, '')
    );

CREATE INDEX CUSIP_VARIANT_CUSIP_ID_IDX ON CUSIP_VARIANT (CUSIP_ID);

CREATE INDEX INFOTABLE_CUSIP_IDX ON INFOTABLE (CUSIP);

CREATE VIEW CUSIP_CURRENT_VARIANT AS
WITH RANKED AS (
    SELECT
        D.CUSIP_ID,
        V.CUSIP_VARIANT_ID,
        D.CUSIP,
        V.REPORTCALENDARORQUARTER,
        V.NAMEOFISSUER,
        V.TITLEOFCLASS,
        V.FIGI,
        V.OCCURRENCE_COUNT,
        ROW_NUMBER() OVER (
            PARTITION BY D.CUSIP_ID
            ORDER BY
                substr(V.REPORTCALENDARORQUARTER, 8, 4) DESC,
                CASE substr(V.REPORTCALENDARORQUARTER, 4, 3)
                    WHEN 'DEC' THEN 12 WHEN 'SEP' THEN 9
                    WHEN 'JUN' THEN 6 WHEN 'MAR' THEN 3 ELSE 0
                END DESC,
                substr(V.REPORTCALENDARORQUARTER, 1, 2) DESC,
                V.OCCURRENCE_COUNT DESC,
                V.NAMEOFISSUER,
                V.TITLEOFCLASS,
                COALESCE(V.FIGI, ''),
                V.CUSIP_VARIANT_ID
        ) AS RN
    FROM CUSIP D
    JOIN CUSIP_VARIANT V USING (CUSIP_ID)
)
SELECT
    CUSIP_ID,
    CUSIP_VARIANT_ID AS CURRENT_CUSIP_VARIANT_ID,
    CUSIP,
    NAMEOFISSUER AS CURRENT_NAMEOFISSUER,
    TITLEOFCLASS AS CURRENT_TITLEOFCLASS,
    FIGI AS CURRENT_FIGI,
    REPORTCALENDARORQUARTER,
    OCCURRENCE_COUNT
FROM RANKED
WHERE RN = 1;

CREATE VIEW CUSIP_13F_HOLDING AS
SELECT
    D.CUSIP_ID,
    V.CUSIP_VARIANT_ID,
    I.CUSIP,
    I.ACCESSION_NUMBER,
    I.INFOTABLE_SK,
    printf('%010d', CAST(S.CIK AS INTEGER)) AS FILING_MANAGER_CIK,
    COALESCE(C.MANAGER_NAME, P.FILINGMANAGER_NAME) AS FILING_MANAGER_NAME,
    S.FILING_DATE,
    S.SUBMISSIONTYPE,
    S.PERIODOFREPORT,
    P.REPORTTYPE,
    P.FORM13FFILENUMBER,
    I.NAMEOFISSUER,
    I.TITLEOFCLASS,
    I.FIGI,
    I.VALUE,
    I.SSHPRNAMT,
    I.SSHPRNAMTTYPE,
    I.PUTCALL,
    I.INVESTMENTDISCRETION,
    I.OTHERMANAGER,
    I.VOTING_AUTH_SOLE,
    I.VOTING_AUTH_SHARED,
    I.VOTING_AUTH_NONE
FROM INFOTABLE I
JOIN SUBMISSION S USING (ACCESSION_NUMBER)
LEFT JOIN COVERPAGE P USING (ACCESSION_NUMBER)
JOIN CUSIP D ON D.CUSIP = I.CUSIP
LEFT JOIN CUSIP_VARIANT V
    ON V.CUSIP_ID = D.CUSIP_ID
   AND V.REPORTCALENDARORQUARTER = P.REPORTCALENDARORQUARTER
   AND V.NAMEOFISSUER = I.NAMEOFISSUER
   AND V.TITLEOFCLASS = I.TITLEOFCLASS
   AND V.FIGI IS I.FIGI
LEFT JOIN CIK C
    ON C.CIK = printf('%010d', CAST(S.CIK AS INTEGER));
