"""SQL used by the application API.

The API only reads materialized analytical tables. Keeping each query here makes
the exact calculation behind every UI component reviewable.
"""

QUARTERS = """
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    Q.QUARTER_END_DATE AS quarter_end_date,
    COUNT(S.CIK_QUARTER_SUMMARY_ID) AS institution_count
FROM QUARTER Q
JOIN CIK_QUARTER_SUMMARY S USING (QUARTER_ID)
GROUP BY Q.QUARTER_ID
ORDER BY Q.QUARTER_ID DESC
"""

OVERVIEW = """
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    COUNT(*) AS institution_count,
    SUM(S.PORTFOLIO_VALUE_USD) AS portfolio_value_usd,
    SUM(S.CUSIP_COUNT) AS reported_position_count,
    SUM(S.COMMON_STOCK_VALUE_USD) AS common_stock_value_usd,
    SUM(S.ETF_VALUE_USD) AS etf_value_usd,
    SUM(S.CALL_VALUE_USD) AS call_value_usd,
    SUM(S.PUT_VALUE_USD) AS put_value_usd
FROM CIK_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
WHERE S.QUARTER_ID = ?
GROUP BY Q.QUARTER_ID
"""

OVERVIEW_INSTITUTIONS = """
SELECT
    S.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        S.MANAGER_CIK) AS institution_name,
    S.PORTFOLIO_VALUE_USD AS portfolio_value_usd,
    S.CUSIP_COUNT AS holding_count
FROM CIK_QUARTER_SUMMARY S
LEFT JOIN CIK C ON C.CIK = S.MANAGER_CIK
WHERE S.QUARTER_ID = ?
ORDER BY S.PORTFOLIO_VALUE_USD DESC, institution_name
LIMIT 5
"""

OVERVIEW_SECURITIES = """
SELECT
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    S.MANAGER_COUNT AS institution_count,
    S.TOTAL_VALUE_USD AS institutional_value_usd
FROM CUSIP_QUARTER_SUMMARY S
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
WHERE S.QUARTER_ID = ?
ORDER BY S.TOTAL_VALUE_USD DESC, issuer
LIMIT 5
"""

INSTITUTIONS = """
SELECT
    S.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        S.MANAGER_CIK) AS institution_name,
    Q.QUARTER_LABEL AS quarter_label,
    S.PORTFOLIO_VALUE_USD AS portfolio_value_usd,
    S.CUSIP_COUNT AS holding_count,
    S.TOP_10_WEIGHT AS top_10_weight,
    S.LARGEST_POSITION_WEIGHT AS largest_position_weight,
    COALESCE(A.new_count, 0) AS new_count,
    COALESCE(A.added_count, 0) AS added_count,
    COALESCE(A.reduced_count, 0) AS reduced_count,
    COALESCE(A.exited_count, 0) AS exited_count,
    COALESCE(A.gross_buy_value_usd, 0) AS gross_buy_value_usd,
    COALESCE(A.gross_sell_value_usd, 0) AS gross_sell_value_usd,
    COALESCE(A.net_value_change_usd, 0) AS net_value_change_usd
FROM CIK_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN CIK C ON C.CIK = S.MANAGER_CIK
LEFT JOIN CIK_QUARTER_ACTIVITY A
  ON A.MANAGER_CIK = S.MANAGER_CIK
 AND A.QUARTER_ID = S.QUARTER_ID
WHERE S.QUARTER_ID = ?
  AND (
      ? = ''
      OR S.MANAGER_CIK LIKE '%' || ? || '%'
      OR C.MANAGER_NAME LIKE '%' || ? || '%'
      OR C.SEC_COMPANY_NAME LIKE '%' || ? || '%'
  )
  {filter_clauses}
ORDER BY {order_expression} {order_direction}, institution_name
LIMIT ? OFFSET ?
"""

INSTITUTION_IDENTITY = """
SELECT
    C.CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        C.CIK) AS institution_name,
    C.SEC_COMPANY_NAME AS sec_company_name,
    C.FILINGMANAGER_STREET1 AS street_1,
    C.FILINGMANAGER_STREET2 AS street_2,
    C.FILINGMANAGER_CITY AS city,
    C.FILINGMANAGER_STATEORCOUNTRY AS state_or_country,
    C.FILINGMANAGER_ZIPCODE AS postal_code,
    C.FORM13FFILENUMBER AS form_13f_file_number,
    C.CRDNUMBER AS crd_number,
    C.LATEST_RELATED_ACCESSION_NUMBER AS latest_accession_number,
    C.LATEST_FILING_DATE AS latest_filing_date,
    MIN(Q.QUARTER_LABEL) AS first_reportable_quarter,
    MAX(Q.QUARTER_LABEL) AS latest_reportable_quarter
FROM CIK C
LEFT JOIN CIK_QUARTER_SUMMARY S ON S.MANAGER_CIK = C.CIK
LEFT JOIN QUARTER Q USING (QUARTER_ID)
WHERE C.CIK = ?
GROUP BY C.CIK
"""

INSTITUTION_SNAPSHOT = """
SELECT
    S.*,
    Q.QUARTER_LABEL AS quarter_label,
    CASE WHEN S.INSTRUMENT_COUNT = 0 THEN NULL
        ELSE 1.0 * S.PORTFOLIO_VALUE_USD / S.INSTRUMENT_COUNT END
        AS average_position_value_usd,
    V.CUSIP AS largest_holding_cusip,
    V.CURRENT_NAMEOFISSUER AS largest_holding_issuer
FROM CIK_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN INSTRUMENT I ON I.INSTRUMENT_ID = S.LARGEST_INSTRUMENT_ID
LEFT JOIN CUSIP_CURRENT_VARIANT V ON V.CUSIP_ID = I.CUSIP_ID
WHERE S.MANAGER_CIK = ? AND S.QUARTER_ID = ?
"""

INSTITUTION_ACTIVITY = """
SELECT
    A.ACTION AS action,
    A.POSITION_COUNT AS position_count,
    A.POSITION_VALUE_USD AS position_value_usd,
    A.AMOUNT_CHANGE AS amount_change,
    A.VALUE_CHANGE_USD AS value_change_usd
FROM CIK_QUARTER_ACTION_ACTIVITY A
WHERE A.MANAGER_CIK = ? AND A.QUARTER_ID = ?
ORDER BY A.ACTION
"""

INSTITUTION_ALLOCATION = """
SELECT
    T.SECURITY_TYPE_CODE AS security_type,
    SUM(P.VALUE_USD) AS value_usd,
    COUNT(*) AS instrument_count
FROM CIK_INSTRUMENT_QUARTER P
JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
WHERE R.MANAGER_CIK = ? AND P.QUARTER_ID = ?
GROUP BY T.SECURITY_TYPE_CODE
ORDER BY value_usd DESC
"""

INSTITUTION_HISTORY = """
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    S.PORTFOLIO_VALUE_USD AS portfolio_value_usd,
    S.CUSIP_COUNT AS holding_count,
    S.TOP_10_WEIGHT AS top_10_weight,
    S.LARGEST_POSITION_WEIGHT AS largest_position_weight,
    CASE WHEN S.INSTRUMENT_COUNT = 0 THEN NULL
        ELSE 1.0 * S.PORTFOLIO_VALUE_USD / S.INSTRUMENT_COUNT END
        AS average_position_value_usd,
    COALESCE(A.new_count, 0) AS new_count,
    COALESCE(A.exited_count, 0) AS exited_count,
    COALESCE(A.net_value_change_usd, 0) AS net_value_change_usd,
    CASE WHEN S.PORTFOLIO_VALUE_USD = 0 THEN NULL
        ELSE 0.5 * COALESCE(A.gross_value_change_usd, 0)
            / S.PORTFOLIO_VALUE_USD END AS turnover_rate
FROM CIK_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN CIK_QUARTER_ACTIVITY A
  ON A.MANAGER_CIK = S.MANAGER_CIK
 AND A.QUARTER_ID = S.QUARTER_ID
WHERE S.MANAGER_CIK = ?
ORDER BY S.QUARTER_ID
"""

INSTITUTION_HOLDINGS = """
WITH HOLDING AS (
    SELECT
        R.CIK_INSTRUMENT_ID,
        R.INSTRUMENT_ID,
        P.VALUE_USD AS MARKET_VALUE_USD,
        P.REPORTED_AMOUNT,
        P.AMOUNT_TYPE,
        P.PORTFOLIO_WEIGHT,
        COALESCE(X.ACTION, 'UNCHANGED') AS ACTION,
        X.AMOUNT_CHANGE,
        X.AMOUNT_CHANGE_PERCENT,
        X.VALUE_CHANGE_USD,
        X.IS_COMPARABLE
    FROM CIK_INSTRUMENT R
    JOIN CIK_INSTRUMENT_QUARTER P USING (CIK_INSTRUMENT_ID)
    LEFT JOIN CIK_INSTRUMENT_CHANGE X
      ON X.CIK_INSTRUMENT_ID = P.CIK_INSTRUMENT_ID
     AND X.TO_QUARTER_ID = P.QUARTER_ID
    WHERE R.MANAGER_CIK = ? AND P.QUARTER_ID = ?

    UNION ALL

    SELECT
        R.CIK_INSTRUMENT_ID,
        R.INSTRUMENT_ID,
        X.PRIOR_VALUE_USD,
        X.PRIOR_REPORTED_AMOUNT,
        I.AMOUNT_TYPE,
        NULL,
        X.ACTION,
        X.AMOUNT_CHANGE,
        X.AMOUNT_CHANGE_PERCENT,
        X.VALUE_CHANGE_USD,
        X.IS_COMPARABLE
    FROM CIK_INSTRUMENT R
    JOIN CIK_INSTRUMENT_CHANGE X USING (CIK_INSTRUMENT_ID)
    JOIN INSTRUMENT I USING (INSTRUMENT_ID)
    LEFT JOIN CIK_INSTRUMENT_QUARTER P
      ON P.CIK_INSTRUMENT_ID = X.CIK_INSTRUMENT_ID
     AND P.QUARTER_ID = X.TO_QUARTER_ID
    WHERE R.MANAGER_CIK = ?
      AND X.TO_QUARTER_ID = ?
      AND P.CIK_INSTRUMENT_QUARTER_ID IS NULL
)
SELECT
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    T.SECURITY_TYPE_CODE AS security_type,
    I.OPTION_TYPE AS option_type,
    H.MARKET_VALUE_USD AS market_value_usd,
    H.REPORTED_AMOUNT AS reported_amount,
    H.AMOUNT_TYPE AS amount_type,
    H.PORTFOLIO_WEIGHT AS portfolio_weight,
    H.ACTION AS action,
    H.AMOUNT_CHANGE AS amount_change,
    H.AMOUNT_CHANGE_PERCENT AS amount_change_percent,
    H.VALUE_CHANGE_USD AS value_change_usd,
    H.IS_COMPARABLE AS is_comparable
FROM HOLDING H
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
WHERE (? = '' OR H.ACTION = ?)
  AND (? = '' OR T.SECURITY_TYPE_CODE = ?)
  AND (
      ? = ''
      OR V.CUSIP LIKE '%' || ? || '%'
      OR V.CURRENT_NAMEOFISSUER LIKE '%' || ? || '%'
  )
ORDER BY {order_expression} {direction}
LIMIT ? OFFSET ?
"""

SECURITIES = """
SELECT
    S.CUSIP_ID AS cusip_id,
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    T.SECURITY_TYPE_CODE AS security_type,
    Q.QUARTER_LABEL AS quarter_label,
    S.MANAGER_COUNT AS institution_count,
    S.TOTAL_VALUE_USD AS institutional_value_usd,
    S.COMMON_STOCK_VALUE_USD AS common_stock_value_usd,
    S.CALL_VALUE_USD AS call_value_usd,
    S.PUT_VALUE_USD AS put_value_usd,
    S.MANAGER_CONCENTRATION_HHI AS concentration_hhi,
    COALESCE(A.new_investor_count, 0) AS new_investor_count,
    COALESCE(A.exited_investor_count, 0) AS exited_investor_count,
    COALESCE(A.added_holder_count, 0) AS added_holder_count,
    COALESCE(A.reduced_holder_count, 0) AS reduced_holder_count,
    COALESCE(A.net_value_change_usd, 0) AS net_value_change_usd
FROM CUSIP_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
LEFT JOIN CUSIP_CLASSIFICATION C USING (CUSIP_ID)
LEFT JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
LEFT JOIN CUSIP_QUARTER_ACTIVITY A
  ON A.CUSIP_ID = S.CUSIP_ID
 AND A.QUARTER_ID = S.QUARTER_ID
WHERE S.QUARTER_ID = ?
  AND (
      ? = ''
      OR V.CUSIP LIKE '%' || ? || '%'
      OR V.CURRENT_NAMEOFISSUER LIKE '%' || ? || '%'
  )
  {filter_clauses}
ORDER BY {order_expression} {order_direction}, issuer
LIMIT ? OFFSET ?
"""

SECURITY_IDENTITY = """
SELECT
    V.CUSIP_ID AS cusip_id,
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    V.CURRENT_FIGI AS figi,
    T.SECURITY_TYPE_CODE AS security_type,
    C.CLASSIFICATION_METHOD AS classification_method,
    C.CLASSIFICATION_CONFIDENCE AS classification_confidence,
    MIN(Q.QUARTER_LABEL) AS first_reportable_quarter,
    MAX(Q.QUARTER_LABEL) AS latest_reportable_quarter
FROM CUSIP_CURRENT_VARIANT V
LEFT JOIN CUSIP_CLASSIFICATION C USING (CUSIP_ID)
LEFT JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
LEFT JOIN CUSIP_QUARTER_SUMMARY S USING (CUSIP_ID)
LEFT JOIN QUARTER Q USING (QUARTER_ID)
WHERE V.CUSIP = ?
GROUP BY V.CUSIP_ID
"""

SECURITY_SNAPSHOT = """
SELECT
    S.*,
    Q.QUARTER_LABEL AS quarter_label,
    CASE WHEN S.MANAGER_COUNT = 0 THEN NULL
        ELSE 1.0 * S.TOTAL_VALUE_USD / S.MANAGER_COUNT END
        AS average_position_value_usd,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        S.LARGEST_MANAGER_CIK) AS largest_holder_name
FROM CUSIP_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN CIK C ON C.CIK = S.LARGEST_MANAGER_CIK
JOIN CUSIP D USING (CUSIP_ID)
WHERE D.CUSIP = ? AND S.QUARTER_ID = ?
"""

SECURITY_ACTIVITY = """
SELECT
    A.ACTION AS action,
    A.INSTITUTION_COUNT AS institution_count,
    A.VALUE_CHANGE_USD AS value_change_usd
FROM CUSIP_BASE_QUARTER_ACTION_ACTIVITY A
JOIN CUSIP D USING (CUSIP_ID)
WHERE D.CUSIP = ?
  AND A.QUARTER_ID = ?
ORDER BY A.ACTION
"""

SECURITY_INSTRUMENT_BREAKDOWN = """
SELECT
    S.OPTION_TYPE AS option_type,
    S.TOTAL_VALUE_USD AS value_usd,
    S.REPORTED_AMOUNT AS reported_amount,
    S.INSTITUTION_COUNT AS institution_count
FROM CUSIP_INSTRUMENT_QUARTER_SUMMARY S
JOIN CUSIP D USING (CUSIP_ID)
WHERE D.CUSIP = ? AND S.QUARTER_ID = ?
ORDER BY CASE S.OPTION_TYPE
    WHEN 'NONE' THEN 1
    WHEN 'CALL' THEN 2
    WHEN 'PUT' THEN 3
    ELSE 4
END
"""

SECURITY_HISTORY = """
WITH BASE_ACTIVITY AS (
    SELECT
        A.QUARTER_ID,
        SUM(CASE WHEN A.ACTION = 'NEW'
            THEN A.INSTITUTION_COUNT ELSE 0 END) AS new_investor_count,
        SUM(CASE WHEN A.ACTION = 'EXITED'
            THEN A.INSTITUTION_COUNT ELSE 0 END) AS exited_investor_count,
        SUM(A.VALUE_CHANGE_USD) AS net_value_change_usd
    FROM CUSIP_BASE_QUARTER_ACTION_ACTIVITY A
    JOIN CUSIP D USING (CUSIP_ID)
    WHERE D.CUSIP = ?
    GROUP BY A.QUARTER_ID
)
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    S.INSTITUTION_COUNT AS institution_count,
    S.TOTAL_VALUE_USD AS institutional_value_usd,
    S.MANAGER_CONCENTRATION_HHI AS concentration_hhi,
    S.AVERAGE_POSITION_VALUE_USD AS average_position_value_usd,
    COALESCE(A.new_investor_count, 0) AS new_investor_count,
    COALESCE(A.exited_investor_count, 0) AS exited_investor_count,
    COALESCE(A.net_value_change_usd, 0) AS net_value_change_usd
FROM CUSIP_INSTRUMENT_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
JOIN CUSIP D USING (CUSIP_ID)
LEFT JOIN BASE_ACTIVITY A USING (QUARTER_ID)
WHERE D.CUSIP = ? AND S.OPTION_TYPE = 'NONE'
ORDER BY S.QUARTER_ID
"""

SECURITY_HOLDERS = """
WITH SECURITY_POSITION AS (
    SELECT
        R.MANAGER_CIK,
        P.CIK_INSTRUMENT_ID,
        I.OPTION_TYPE,
        I.AMOUNT_TYPE,
        P.VALUE_USD AS MARKET_VALUE_USD,
        P.REPORTED_AMOUNT,
        P.PORTFOLIO_WEIGHT,
        COALESCE(X.ACTION, 'UNCHANGED') AS ACTION,
        X.AMOUNT_CHANGE,
        X.VALUE_CHANGE_USD
    FROM CUSIP D
    CROSS JOIN INSTRUMENT I
      ON I.CUSIP_ID = D.CUSIP_ID
    CROSS JOIN CIK_INSTRUMENT R
      ON R.INSTRUMENT_ID = I.INSTRUMENT_ID
    CROSS JOIN CIK_INSTRUMENT_QUARTER P
      ON P.CIK_INSTRUMENT_ID = R.CIK_INSTRUMENT_ID
     AND P.QUARTER_ID = ?
    LEFT JOIN CIK_INSTRUMENT_CHANGE X
      ON X.CIK_INSTRUMENT_ID = P.CIK_INSTRUMENT_ID
     AND X.TO_QUARTER_ID = P.QUARTER_ID
    WHERE D.CUSIP = ?

    UNION ALL

    SELECT
        R.MANAGER_CIK,
        X.CIK_INSTRUMENT_ID,
        I.OPTION_TYPE,
        I.AMOUNT_TYPE,
        0 AS MARKET_VALUE_USD,
        0 AS REPORTED_AMOUNT,
        0.0 AS PORTFOLIO_WEIGHT,
        X.ACTION,
        X.AMOUNT_CHANGE,
        X.VALUE_CHANGE_USD
    FROM CUSIP D
    CROSS JOIN INSTRUMENT I
      ON I.CUSIP_ID = D.CUSIP_ID
    CROSS JOIN CIK_INSTRUMENT R
      ON R.INSTRUMENT_ID = I.INSTRUMENT_ID
    CROSS JOIN CIK_INSTRUMENT_CHANGE X
      ON X.CIK_INSTRUMENT_ID = R.CIK_INSTRUMENT_ID
     AND X.TO_QUARTER_ID = ?
    LEFT JOIN CIK_INSTRUMENT_QUARTER P
      ON P.CIK_INSTRUMENT_ID = X.CIK_INSTRUMENT_ID
     AND P.QUARTER_ID = X.TO_QUARTER_ID
    WHERE D.CUSIP = ?
      AND P.CIK_INSTRUMENT_QUARTER_ID IS NULL
),
HOLDER AS (
    SELECT
        S.MANAGER_CIK,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE'
            THEN S.MARKET_VALUE_USD END) AS MARKET_VALUE_USD,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE'
            THEN S.REPORTED_AMOUNT END) AS REPORTED_AMOUNT,
        GROUP_CONCAT(DISTINCT CASE WHEN S.OPTION_TYPE = 'NONE'
            THEN S.AMOUNT_TYPE END) AS AMOUNT_TYPE,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE' AND S.AMOUNT_TYPE = 'SH'
            THEN S.REPORTED_AMOUNT END) AS SHARES,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE' AND S.AMOUNT_TYPE = 'PRN'
            THEN S.REPORTED_AMOUNT END) AS PRINCIPAL_AMOUNT,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE' AND S.AMOUNT_TYPE = 'OTHER'
            THEN S.REPORTED_AMOUNT END) AS OTHER_AMOUNT,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE'
            THEN S.PORTFOLIO_WEIGHT END) AS PORTFOLIO_WEIGHT,
        CASE
            WHEN SUM(S.OPTION_TYPE = 'NONE' AND S.ACTION = 'UNKNOWN') > 0
                THEN 'UNKNOWN'
            WHEN SUM(S.OPTION_TYPE = 'NONE' AND S.ACTION = 'NEW') > 0
                THEN 'NEW'
            WHEN SUM(S.OPTION_TYPE = 'NONE' AND S.ACTION = 'ADDED') > 0
                THEN 'ADDED'
            WHEN SUM(S.OPTION_TYPE = 'NONE' AND S.ACTION = 'REDUCED') > 0
                THEN 'REDUCED'
            WHEN SUM(S.OPTION_TYPE = 'NONE' AND S.ACTION = 'EXITED') > 0
                THEN 'EXITED'
            WHEN SUM(S.OPTION_TYPE = 'NONE') > 0 THEN 'UNCHANGED'
            ELSE NULL
        END AS ACTION,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE'
            THEN COALESCE(S.AMOUNT_CHANGE, 0) END) AS AMOUNT_CHANGE,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE' AND S.AMOUNT_TYPE = 'SH'
            THEN COALESCE(S.AMOUNT_CHANGE, 0) END) AS SHARE_CHANGE,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE' AND S.AMOUNT_TYPE = 'PRN'
            THEN COALESCE(S.AMOUNT_CHANGE, 0) END) AS PRINCIPAL_AMOUNT_CHANGE,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE' AND S.AMOUNT_TYPE = 'OTHER'
            THEN COALESCE(S.AMOUNT_CHANGE, 0) END) AS OTHER_AMOUNT_CHANGE,
        SUM(CASE WHEN S.OPTION_TYPE = 'NONE'
            THEN COALESCE(S.VALUE_CHANGE_USD, 0) END) AS VALUE_CHANGE_USD,
        SUM(CASE WHEN S.OPTION_TYPE = 'CALL'
            THEN S.MARKET_VALUE_USD END) AS CALL_VALUE_USD,
        SUM(CASE WHEN S.OPTION_TYPE = 'CALL'
            THEN S.REPORTED_AMOUNT END) AS CALL_REPORTED_AMOUNT,
        SUM(CASE WHEN S.OPTION_TYPE = 'PUT'
            THEN S.MARKET_VALUE_USD END) AS PUT_VALUE_USD,
        SUM(CASE WHEN S.OPTION_TYPE = 'PUT'
            THEN S.REPORTED_AMOUNT END) AS PUT_REPORTED_AMOUNT
    FROM SECURITY_POSITION S
    GROUP BY S.MANAGER_CIK
)
SELECT
    H.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        H.MANAGER_CIK) AS institution_name,
    H.MARKET_VALUE_USD AS market_value_usd,
    H.REPORTED_AMOUNT AS reported_amount,
    H.AMOUNT_TYPE AS amount_type,
    H.SHARES AS shares,
    H.PRINCIPAL_AMOUNT AS principal_amount,
    H.OTHER_AMOUNT AS other_amount,
    H.PORTFOLIO_WEIGHT AS portfolio_weight,
    H.ACTION AS action,
    H.AMOUNT_CHANGE AS amount_change,
    H.SHARE_CHANGE AS share_change,
    H.PRINCIPAL_AMOUNT_CHANGE AS principal_amount_change,
    H.OTHER_AMOUNT_CHANGE AS other_amount_change,
    H.VALUE_CHANGE_USD AS value_change_usd,
    H.CALL_VALUE_USD AS call_value_usd,
    H.CALL_REPORTED_AMOUNT AS call_reported_amount,
    H.PUT_VALUE_USD AS put_value_usd,
    H.PUT_REPORTED_AMOUNT AS put_reported_amount
FROM HOLDER H
LEFT JOIN CIK C ON C.CIK = H.MANAGER_CIK
WHERE (? = '' OR H.ACTION = ?)
  AND (
      ? = ''
      OR H.MANAGER_CIK LIKE '%' || ? || '%'
      OR C.MANAGER_NAME LIKE '%' || ? || '%'
      OR C.SEC_COMPANY_NAME LIKE '%' || ? || '%'
  )
ORDER BY {order_expression} DESC
LIMIT ? OFFSET ?
"""

RELATIONSHIP_IDENTITY = """
SELECT
    R.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        R.MANAGER_CIK) AS institution_name,
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    MIN(Q.QUARTER_LABEL) AS first_purchased,
    MAX(Q.QUARTER_LABEL) AS latest_quarter
FROM CIK_INSTRUMENT R
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
LEFT JOIN CIK C ON C.CIK = R.MANAGER_CIK
JOIN CIK_INSTRUMENT_QUARTER P USING (CIK_INSTRUMENT_ID)
JOIN QUARTER Q USING (QUARTER_ID)
WHERE R.MANAGER_CIK = ? AND V.CUSIP = ?
GROUP BY R.MANAGER_CIK, V.CUSIP
"""

RELATIONSHIP_HISTORY = """
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    SUM(P.VALUE_USD) AS market_value_usd,
    CASE WHEN COUNT(DISTINCT I.AMOUNT_TYPE) = 1
        THEN SUM(P.REPORTED_AMOUNT) END AS reported_amount,
    SUM(CASE WHEN I.AMOUNT_TYPE = 'SH'
        THEN P.REPORTED_AMOUNT END) AS shares,
    SUM(CASE WHEN I.AMOUNT_TYPE = 'PRN'
        THEN P.REPORTED_AMOUNT END) AS principal_amount,
    GROUP_CONCAT(DISTINCT I.AMOUNT_TYPE) AS amount_type,
    MAX(P.PORTFOLIO_WEIGHT) AS portfolio_weight,
    COALESCE(MAX(X.ACTION), 'UNCHANGED') AS action,
    CASE WHEN COUNT(DISTINCT I.AMOUNT_TYPE) = 1
        THEN SUM(COALESCE(X.AMOUNT_CHANGE, 0)) END AS amount_change,
    CASE WHEN COUNT(DISTINCT I.AMOUNT_TYPE) = 1
        THEN MAX(X.AMOUNT_CHANGE_PERCENT) END AS amount_change_percent,
    SUM(COALESCE(X.VALUE_CHANGE_USD, 0)) AS value_change_usd
FROM CIK_INSTRUMENT_QUARTER P
JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN CUSIP D USING (CUSIP_ID)
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN CIK_INSTRUMENT_CHANGE X
  ON X.CIK_INSTRUMENT_ID = P.CIK_INSTRUMENT_ID
 AND X.TO_QUARTER_ID = P.QUARTER_ID
WHERE R.MANAGER_CIK = ? AND D.CUSIP = ?
  AND I.OPTION_TYPE = 'NONE'
GROUP BY P.QUARTER_ID
ORDER BY P.QUARTER_ID
"""

RELATIONSHIP_OPTION_HISTORY = """
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    I.OPTION_TYPE AS option_type,
    SUM(P.VALUE_USD) AS market_value_usd,
    SUM(P.REPORTED_AMOUNT) AS reported_amount,
    GROUP_CONCAT(DISTINCT I.AMOUNT_TYPE) AS amount_type
FROM CIK_INSTRUMENT_QUARTER P
JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN CUSIP D USING (CUSIP_ID)
JOIN QUARTER Q USING (QUARTER_ID)
WHERE R.MANAGER_CIK = ? AND D.CUSIP = ?
  AND I.OPTION_TYPE IN ('CALL', 'PUT')
GROUP BY P.QUARTER_ID, I.OPTION_TYPE
ORDER BY P.QUARTER_ID, I.OPTION_TYPE
"""

COMPARE_INSTITUTION = """
WITH SNAPSHOT AS (
    SELECT
        S.MANAGER_CIK,
        S.QUARTER_ID,
        Q.QUARTER_LABEL,
        S.PORTFOLIO_VALUE_USD,
        S.CUSIP_COUNT,
        S.INSTRUMENT_COUNT,
        S.TOP_10_WEIGHT,
        S.COMMON_STOCK_VALUE_USD,
        S.ETF_VALUE_USD,
        S.CALL_VALUE_USD,
        S.PUT_VALUE_USD,
        COALESCE(A.NEW_COUNT, 0) AS NEW_COUNT,
        COALESCE(A.EXITED_COUNT, 0) AS EXITED_COUNT,
        COALESCE(A.NET_VALUE_CHANGE_USD, 0) AS NET_VALUE_CHANGE_USD
    FROM CIK_QUARTER_SUMMARY S
    JOIN QUARTER Q USING (QUARTER_ID)
    LEFT JOIN CIK_QUARTER_ACTIVITY A
      ON A.MANAGER_CIK = S.MANAGER_CIK
     AND A.QUARTER_ID = S.QUARTER_ID
    WHERE S.MANAGER_CIK = ?
      AND S.QUARTER_ID IN (?, ?)
)
SELECT * FROM SNAPSHOT ORDER BY QUARTER_ID
"""

COMPARE_INSTITUTION_MOVERS = """
WITH MANAGER_PERIOD AS (
    SELECT
        MANAGER_CIK,
        MAX(CASE WHEN QUARTER_ID = ?
            THEN HAS_CONFIDENTIAL_OMISSION ELSE 0 END)
            AS PRIOR_HAS_CONFIDENTIAL_OMISSION,
        MAX(CASE WHEN QUARTER_ID = ?
            THEN HAS_CONFIDENTIAL_OMISSION ELSE 0 END)
            AS CURRENT_HAS_CONFIDENTIAL_OMISSION
    FROM CIK_QUARTER_SUMMARY
    WHERE MANAGER_CIK = ?
      AND QUARTER_ID IN (?, ?)
    GROUP BY MANAGER_CIK
),
SCOPE AS MATERIALIZED (
    SELECT
        R.CIK_INSTRUMENT_ID,
        I.CUSIP_ID,
        I.SECURITY_TYPE_ID,
        I.AMOUNT_TYPE
    FROM CIK_INSTRUMENT R
    JOIN MANAGER_PERIOD M USING (MANAGER_CIK)
    JOIN INSTRUMENT I USING (INSTRUMENT_ID)
    WHERE I.OPTION_TYPE = 'NONE'
),
POSITION_KEYS AS (
    SELECT S.CIK_INSTRUMENT_ID
    FROM SCOPE S
    JOIN CIK_INSTRUMENT_QUARTER P USING (CIK_INSTRUMENT_ID)
    WHERE P.QUARTER_ID = ?
    UNION
    SELECT S.CIK_INSTRUMENT_ID
    FROM SCOPE S
    JOIN CIK_INSTRUMENT_QUARTER P USING (CIK_INSTRUMENT_ID)
    WHERE P.QUARTER_ID = ?
),
MOVED AS (
    SELECT
        S.CIK_INSTRUMENT_ID,
        S.CUSIP_ID,
        S.SECURITY_TYPE_ID,
        S.AMOUNT_TYPE,
        CASE
            WHEN P.CIK_INSTRUMENT_QUARTER_ID IS NULL
             AND M.PRIOR_HAS_CONFIDENTIAL_OMISSION = 1
                THEN 'UNKNOWN'
            WHEN C.CIK_INSTRUMENT_QUARTER_ID IS NULL
             AND M.CURRENT_HAS_CONFIDENTIAL_OMISSION = 1
                THEN 'UNKNOWN'
            WHEN P.CIK_INSTRUMENT_QUARTER_ID IS NULL THEN 'NEW'
            WHEN C.CIK_INSTRUMENT_QUARTER_ID IS NULL THEN 'EXITED'
            WHEN C.REPORTED_AMOUNT > P.REPORTED_AMOUNT THEN 'ADDED'
            WHEN C.REPORTED_AMOUNT < P.REPORTED_AMOUNT THEN 'REDUCED'
            ELSE 'UNCHANGED'
        END AS ACTION,
        COALESCE(P.VALUE_USD, 0) AS PRIOR_VALUE_USD,
        COALESCE(C.VALUE_USD, 0) AS CURRENT_VALUE_USD,
        COALESCE(C.VALUE_USD, 0) - COALESCE(P.VALUE_USD, 0)
            AS VALUE_CHANGE_USD,
        COALESCE(P.REPORTED_AMOUNT, 0) AS PRIOR_REPORTED_AMOUNT,
        COALESCE(C.REPORTED_AMOUNT, 0) AS CURRENT_REPORTED_AMOUNT,
        COALESCE(C.REPORTED_AMOUNT, 0) - COALESCE(P.REPORTED_AMOUNT, 0)
            AS AMOUNT_CHANGE
    FROM POSITION_KEYS K
    JOIN SCOPE S USING (CIK_INSTRUMENT_ID)
    CROSS JOIN MANAGER_PERIOD M
    LEFT JOIN CIK_INSTRUMENT_QUARTER P
      ON P.CIK_INSTRUMENT_ID = K.CIK_INSTRUMENT_ID
     AND P.QUARTER_ID = ?
    LEFT JOIN CIK_INSTRUMENT_QUARTER C
      ON C.CIK_INSTRUMENT_ID = K.CIK_INSTRUMENT_ID
     AND C.QUARTER_ID = ?
)
SELECT
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    T.SECURITY_TYPE_CODE AS security_type,
    M.AMOUNT_TYPE AS amount_type,
    M.ACTION AS action,
    M.PRIOR_VALUE_USD AS prior_value_usd,
    M.CURRENT_VALUE_USD AS current_value_usd,
    M.VALUE_CHANGE_USD AS value_change_usd,
    M.PRIOR_REPORTED_AMOUNT AS prior_reported_amount,
    M.CURRENT_REPORTED_AMOUNT AS current_reported_amount,
    M.AMOUNT_CHANGE AS amount_change
FROM MOVED M
JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
WHERE (? = '' OR M.ACTION = ?)
ORDER BY ABS(M.VALUE_CHANGE_USD) DESC
LIMIT ?
"""

COMPARE_SECURITY = """
SELECT
    S.CUSIP_ID,
    S.QUARTER_ID,
    Q.QUARTER_LABEL,
    S.TOTAL_VALUE_USD,
    S.MANAGER_COUNT,
    S.COMMON_STOCK_VALUE_USD,
    S.ETF_VALUE_USD,
    S.CALL_VALUE_USD,
    S.PUT_VALUE_USD,
    S.MANAGER_CONCENTRATION_HHI,
    COALESCE(A.NEW_INVESTOR_COUNT, 0) AS NEW_INVESTOR_COUNT,
    COALESCE(A.EXITED_INVESTOR_COUNT, 0) AS EXITED_INVESTOR_COUNT,
    COALESCE(A.NET_VALUE_CHANGE_USD, 0) AS NET_VALUE_CHANGE_USD
FROM CUSIP_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
JOIN CUSIP D USING (CUSIP_ID)
LEFT JOIN CUSIP_QUARTER_ACTIVITY A
  ON A.CUSIP_ID = S.CUSIP_ID
 AND A.QUARTER_ID = S.QUARTER_ID
WHERE D.CUSIP = ?
  AND S.QUARTER_ID IN (?, ?)
ORDER BY S.QUARTER_ID
"""

COMPARE_SECURITY_MOVERS = """
WITH SCOPE AS MATERIALIZED (
    SELECT
        R.CIK_INSTRUMENT_ID,
        R.MANAGER_CIK,
        I.AMOUNT_TYPE
    FROM CUSIP D
    JOIN INSTRUMENT I USING (CUSIP_ID)
    JOIN CIK_INSTRUMENT R USING (INSTRUMENT_ID)
    WHERE D.CUSIP = ?
      AND I.OPTION_TYPE = 'NONE'
),
MANAGER_PERIOD AS MATERIALIZED (
    SELECT
        S.MANAGER_CIK,
        COALESCE(MAX(CASE WHEN Q.QUARTER_ID = ?
            THEN Q.HAS_CONFIDENTIAL_OMISSION ELSE 0 END), 0)
            AS PRIOR_HAS_CONFIDENTIAL_OMISSION,
        COALESCE(MAX(CASE WHEN Q.QUARTER_ID = ?
            THEN Q.HAS_CONFIDENTIAL_OMISSION ELSE 0 END), 0)
            AS CURRENT_HAS_CONFIDENTIAL_OMISSION
    FROM (SELECT DISTINCT MANAGER_CIK FROM SCOPE) S
    LEFT JOIN CIK_QUARTER_SUMMARY Q
      ON Q.MANAGER_CIK = S.MANAGER_CIK
     AND Q.QUARTER_ID IN (?, ?)
    GROUP BY S.MANAGER_CIK
),
POSITION_KEYS AS (
    SELECT S.CIK_INSTRUMENT_ID
    FROM SCOPE S
    JOIN CIK_INSTRUMENT_QUARTER P USING (CIK_INSTRUMENT_ID)
    WHERE P.QUARTER_ID = ?
    UNION
    SELECT S.CIK_INSTRUMENT_ID
    FROM SCOPE S
    JOIN CIK_INSTRUMENT_QUARTER P USING (CIK_INSTRUMENT_ID)
    WHERE P.QUARTER_ID = ?
),
MOVED AS (
    SELECT
        S.CIK_INSTRUMENT_ID,
        S.MANAGER_CIK,
        S.AMOUNT_TYPE,
        CASE
            WHEN P.CIK_INSTRUMENT_QUARTER_ID IS NULL
             AND M.PRIOR_HAS_CONFIDENTIAL_OMISSION = 1
                THEN 'UNKNOWN'
            WHEN C.CIK_INSTRUMENT_QUARTER_ID IS NULL
             AND M.CURRENT_HAS_CONFIDENTIAL_OMISSION = 1
                THEN 'UNKNOWN'
            WHEN P.CIK_INSTRUMENT_QUARTER_ID IS NULL THEN 'NEW'
            WHEN C.CIK_INSTRUMENT_QUARTER_ID IS NULL THEN 'EXITED'
            WHEN C.REPORTED_AMOUNT > P.REPORTED_AMOUNT THEN 'ADDED'
            WHEN C.REPORTED_AMOUNT < P.REPORTED_AMOUNT THEN 'REDUCED'
            ELSE 'UNCHANGED'
        END AS ACTION,
        COALESCE(P.VALUE_USD, 0) AS PRIOR_VALUE_USD,
        COALESCE(C.VALUE_USD, 0) AS CURRENT_VALUE_USD,
        COALESCE(C.VALUE_USD, 0) - COALESCE(P.VALUE_USD, 0)
            AS VALUE_CHANGE_USD,
        COALESCE(P.REPORTED_AMOUNT, 0) AS PRIOR_REPORTED_AMOUNT,
        COALESCE(C.REPORTED_AMOUNT, 0) AS CURRENT_REPORTED_AMOUNT,
        COALESCE(C.REPORTED_AMOUNT, 0) - COALESCE(P.REPORTED_AMOUNT, 0)
            AS AMOUNT_CHANGE
    FROM POSITION_KEYS K
    JOIN SCOPE S USING (CIK_INSTRUMENT_ID)
    JOIN MANAGER_PERIOD M USING (MANAGER_CIK)
    LEFT JOIN CIK_INSTRUMENT_QUARTER P
      ON P.CIK_INSTRUMENT_ID = K.CIK_INSTRUMENT_ID
     AND P.QUARTER_ID = ?
    LEFT JOIN CIK_INSTRUMENT_QUARTER C
      ON C.CIK_INSTRUMENT_ID = K.CIK_INSTRUMENT_ID
     AND C.QUARTER_ID = ?
)
SELECT
    M.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        M.MANAGER_CIK) AS institution_name,
    M.AMOUNT_TYPE AS amount_type,
    M.ACTION AS action,
    M.PRIOR_VALUE_USD AS prior_value_usd,
    M.CURRENT_VALUE_USD AS current_value_usd,
    M.VALUE_CHANGE_USD AS value_change_usd,
    M.PRIOR_REPORTED_AMOUNT AS prior_reported_amount,
    M.CURRENT_REPORTED_AMOUNT AS current_reported_amount,
    M.AMOUNT_CHANGE AS amount_change
FROM MOVED M
LEFT JOIN CIK C ON C.CIK = M.MANAGER_CIK
WHERE (? = '' OR M.ACTION = ?)
ORDER BY ABS(M.VALUE_CHANGE_USD) DESC
LIMIT ?
"""

ACTIVITY_EXPLORER = """
SELECT
    R.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        R.MANAGER_CIK) AS institution_name,
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    T.SECURITY_TYPE_CODE AS security_type,
    X.ACTION AS action,
    X.PRIOR_VALUE_USD AS prior_value_usd,
    X.CURRENT_VALUE_USD AS current_value_usd,
    X.VALUE_CHANGE_USD AS value_change_usd,
    X.PRIOR_REPORTED_AMOUNT AS prior_reported_amount,
    X.CURRENT_REPORTED_AMOUNT AS current_reported_amount,
    X.AMOUNT_CHANGE AS amount_change
FROM CIK_INSTRUMENT_CHANGE X
JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
LEFT JOIN CIK C ON C.CIK = R.MANAGER_CIK
WHERE X.TO_QUARTER_ID = ?
  AND (? = '' OR X.ACTION = ?)
  AND (? = '' OR R.MANAGER_CIK = ?)
  AND (? = '' OR V.CUSIP = ?)
  AND (
      ? = ''
      OR R.MANAGER_CIK LIKE '%' || ? || '%'
      OR C.MANAGER_NAME LIKE '%' || ? || '%'
      OR C.SEC_COMPANY_NAME LIKE '%' || ? || '%'
      OR V.CUSIP LIKE '%' || ? || '%'
      OR V.CURRENT_NAMEOFISSUER LIKE '%' || ? || '%'
  )
ORDER BY ABS(COALESCE(X.VALUE_CHANGE_USD, 0)) DESC
LIMIT ? OFFSET ?
"""

SIC_DIVISION_AGGREGATION = """
WITH CIK_SIC AS (
    SELECT
        CIK,
        COALESCE(NULLIF(MIN(SIC_MAJOR_GROUP_DIVISION), ''), 'Unclassified')
            AS DIVISION,
        COALESCE(NULLIF(MIN(SIC_DESCRIPTION), ''), 'Unclassified')
            AS SIC_DESCRIPTION
    FROM CIK_TICKER_EXCHANGE
    GROUP BY CIK
)
SELECT
    COALESCE(CS.DIVISION, 'Unclassified') AS division,
    COUNT(*) AS institution_count,
    SUM(S.PORTFOLIO_VALUE_USD) AS portfolio_value_usd,
    SUM(S.CUSIP_COUNT) AS holding_count,
    SUM(S.COMMON_STOCK_VALUE_USD) AS common_stock_value_usd,
    SUM(S.ETF_VALUE_USD) AS etf_value_usd,
    SUM(S.CALL_VALUE_USD) AS call_value_usd,
    SUM(S.PUT_VALUE_USD) AS put_value_usd,
    SUM(COALESCE(A.NET_VALUE_CHANGE_USD, 0)) AS net_value_change_usd,
    SUM(COALESCE(A.NEW_COUNT, 0)) AS new_count,
    SUM(COALESCE(A.EXITED_COUNT, 0)) AS exited_count
FROM CIK_QUARTER_SUMMARY S
LEFT JOIN CIK_SIC CS ON CS.CIK = S.MANAGER_CIK
LEFT JOIN CIK_QUARTER_ACTIVITY A
  ON A.MANAGER_CIK = S.MANAGER_CIK
 AND A.QUARTER_ID = S.QUARTER_ID
WHERE S.QUARTER_ID = ?
GROUP BY COALESCE(CS.DIVISION, 'Unclassified')
ORDER BY portfolio_value_usd DESC
"""

SIC_INDUSTRY_AGGREGATION = """
WITH CIK_SIC AS (
    SELECT
        CIK,
        COALESCE(NULLIF(MIN(SIC_MAJOR_GROUP_DIVISION), ''), 'Unclassified')
            AS DIVISION,
        COALESCE(NULLIF(MIN(SIC), ''), '----') AS SIC,
        COALESCE(NULLIF(MIN(SIC_DESCRIPTION), ''), 'Unclassified')
            AS SIC_DESCRIPTION
    FROM CIK_TICKER_EXCHANGE
    GROUP BY CIK
)
SELECT
    COALESCE(CS.DIVISION, 'Unclassified') AS division,
    COALESCE(CS.SIC, '----') AS sic,
    COALESCE(CS.SIC_DESCRIPTION, 'Unclassified') AS sic_description,
    COUNT(*) AS institution_count,
    SUM(S.PORTFOLIO_VALUE_USD) AS portfolio_value_usd,
    SUM(S.CUSIP_COUNT) AS holding_count,
    SUM(COALESCE(A.NET_VALUE_CHANGE_USD, 0)) AS net_value_change_usd,
    SUM(COALESCE(A.NEW_COUNT, 0)) AS new_count,
    SUM(COALESCE(A.EXITED_COUNT, 0)) AS exited_count
FROM CIK_QUARTER_SUMMARY S
LEFT JOIN CIK_SIC CS ON CS.CIK = S.MANAGER_CIK
LEFT JOIN CIK_QUARTER_ACTIVITY A
  ON A.MANAGER_CIK = S.MANAGER_CIK
 AND A.QUARTER_ID = S.QUARTER_ID
WHERE S.QUARTER_ID = ?
  AND (? = '' OR CS.DIVISION = ?)
GROUP BY
    COALESCE(CS.DIVISION, 'Unclassified'),
    COALESCE(CS.SIC, '----'),
    COALESCE(CS.SIC_DESCRIPTION, 'Unclassified')
ORDER BY portfolio_value_usd DESC
LIMIT ?
"""

GLOBAL_SEARCH = """
SELECT 'institution' AS result_type, C.CIK AS result_id,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        C.CIK) AS label,
    'CIK ' || C.CIK AS detail
FROM CIK C
WHERE C.CIK LIKE ? OR C.MANAGER_NAME LIKE ? OR C.SEC_COMPANY_NAME LIKE ?
UNION ALL
SELECT 'security', V.CUSIP, V.CURRENT_NAMEOFISSUER,
    V.CUSIP || ' · ' || COALESCE(V.CURRENT_TITLEOFCLASS, 'Unclassified')
FROM CUSIP_CURRENT_VARIANT V
WHERE V.CUSIP LIKE ? OR V.CURRENT_NAMEOFISSUER LIKE ?
LIMIT 12
"""
