"""SQL used by the application API.

The API only reads materialized analytical tables. Keeping each query here makes
the exact calculation behind every UI component reviewable.
"""

QUARTERS = """
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    Q.QUARTER_END_DATE AS quarter_end_date,
    COUNT(S.CIK_QUARTER_SUMMARY_ID) AS institution_count
FROM QUARTER Q
JOIN CIK_QUARTER_SUMMARY S USING (QUARTER_ID)
GROUP BY Q.QUARTER_ID
ORDER BY Q.QUARTER_ID DESC
"""

OVERVIEW = """
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    COUNT(*) AS institution_count,
    SUM(S.PORTFOLIO_VALUE_USD) AS portfolio_value_usd,
    SUM(S.CUSIP_COUNT) AS reported_position_count,
    SUM(S.COMMON_STOCK_VALUE_USD) AS common_stock_value_usd,
    SUM(S.ETF_VALUE_USD) AS etf_value_usd,
    SUM(S.CALL_VALUE_USD) AS call_value_usd,
    SUM(S.PUT_VALUE_USD) AS put_value_usd
FROM CIK_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
WHERE S.QUARTER_ID = ?
GROUP BY Q.QUARTER_ID
"""

OVERVIEW_INSTITUTIONS = """
SELECT
    S.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        S.MANAGER_CIK) AS institution_name,
    S.PORTFOLIO_VALUE_USD AS portfolio_value_usd,
    S.CUSIP_COUNT AS holding_count
FROM CIK_QUARTER_SUMMARY S
LEFT JOIN CIK C ON C.CIK = S.MANAGER_CIK
WHERE S.QUARTER_ID = ?
ORDER BY S.PORTFOLIO_VALUE_USD DESC, institution_name
LIMIT 5
"""

OVERVIEW_SECURITIES = """
SELECT
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    S.MANAGER_COUNT AS institution_count,
    S.TOTAL_VALUE_USD AS institutional_value_usd
FROM CUSIP_QUARTER_SUMMARY S
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
WHERE S.QUARTER_ID = ?
ORDER BY S.TOTAL_VALUE_USD DESC, issuer
LIMIT 5
"""

INSTITUTIONS = """
WITH ACTIVITY AS (
    SELECT
        R.MANAGER_CIK,
        COUNT(*) FILTER (WHERE X.ACTION = 'NEW') AS new_count,
        COUNT(*) FILTER (WHERE X.ACTION = 'ADDED') AS added_count,
        COUNT(*) FILTER (WHERE X.ACTION = 'REDUCED') AS reduced_count,
        COUNT(*) FILTER (WHERE X.ACTION = 'EXITED') AS exited_count,
        SUM(CASE
            WHEN X.ACTION IN ('NEW', 'ADDED')
            THEN COALESCE(X.VALUE_CHANGE_USD, X.CURRENT_VALUE_USD, 0)
            ELSE 0 END) AS gross_buy_value_usd,
        SUM(CASE
            WHEN X.ACTION IN ('REDUCED', 'EXITED')
            THEN ABS(COALESCE(X.VALUE_CHANGE_USD, X.PRIOR_VALUE_USD, 0))
            ELSE 0 END) AS gross_sell_value_usd,
        SUM(CASE WHEN X.IS_COMPARABLE = 1
            THEN COALESCE(X.VALUE_CHANGE_USD, 0) ELSE 0 END)
            AS net_value_change_usd
    FROM CIK_INSTRUMENT_CHANGE X
    JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
    WHERE X.TO_QUARTER_ID = ?
    GROUP BY R.MANAGER_CIK
)
SELECT
    S.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        S.MANAGER_CIK) AS institution_name,
    Q.QUARTER_LABEL AS quarter_label,
    S.PORTFOLIO_VALUE_USD AS portfolio_value_usd,
    S.CUSIP_COUNT AS holding_count,
    S.TOP_10_WEIGHT AS top_10_weight,
    S.LARGEST_POSITION_WEIGHT AS largest_position_weight,
    COALESCE(A.new_count, 0) AS new_count,
    COALESCE(A.added_count, 0) AS added_count,
    COALESCE(A.reduced_count, 0) AS reduced_count,
    COALESCE(A.exited_count, 0) AS exited_count,
    COALESCE(A.gross_buy_value_usd, 0) AS gross_buy_value_usd,
    COALESCE(A.gross_sell_value_usd, 0) AS gross_sell_value_usd,
    COALESCE(A.net_value_change_usd, 0) AS net_value_change_usd
FROM CIK_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN CIK C ON C.CIK = S.MANAGER_CIK
LEFT JOIN ACTIVITY A ON A.MANAGER_CIK = S.MANAGER_CIK
WHERE S.QUARTER_ID = ?
  AND (
      ? = ''
      OR S.MANAGER_CIK LIKE '%' || ? || '%'
      OR C.MANAGER_NAME LIKE '%' || ? || '%'
      OR C.SEC_COMPANY_NAME LIKE '%' || ? || '%'
  )
  {filter_clauses}
ORDER BY {order_expression} {order_direction}, institution_name
LIMIT ? OFFSET ?
"""

INSTITUTION_IDENTITY = """
SELECT
    C.CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        C.CIK) AS institution_name,
    C.SEC_COMPANY_NAME AS sec_company_name,
    C.FILINGMANAGER_STREET1 AS street_1,
    C.FILINGMANAGER_STREET2 AS street_2,
    C.FILINGMANAGER_CITY AS city,
    C.FILINGMANAGER_STATEORCOUNTRY AS state_or_country,
    C.FILINGMANAGER_ZIPCODE AS postal_code,
    C.FORM13FFILENUMBER AS form_13f_file_number,
    C.CRDNUMBER AS crd_number,
    C.LATEST_RELATED_ACCESSION_NUMBER AS latest_accession_number,
    C.LATEST_FILING_DATE AS latest_filing_date,
    MIN(Q.QUARTER_LABEL) AS first_reportable_quarter,
    MAX(Q.QUARTER_LABEL) AS latest_reportable_quarter
FROM CIK C
LEFT JOIN CIK_QUARTER_SUMMARY S ON S.MANAGER_CIK = C.CIK
LEFT JOIN QUARTER Q USING (QUARTER_ID)
WHERE C.CIK = ?
GROUP BY C.CIK
"""

INSTITUTION_SNAPSHOT = """
SELECT
    S.*,
    Q.QUARTER_LABEL AS quarter_label,
    CASE WHEN S.INSTRUMENT_COUNT = 0 THEN NULL
        ELSE 1.0 * S.PORTFOLIO_VALUE_USD / S.INSTRUMENT_COUNT END
        AS average_position_value_usd,
    V.CUSIP AS largest_holding_cusip,
    V.CURRENT_NAMEOFISSUER AS largest_holding_issuer
FROM CIK_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN INSTRUMENT I ON I.INSTRUMENT_ID = S.LARGEST_INSTRUMENT_ID
LEFT JOIN CUSIP_CURRENT_VARIANT V ON V.CUSIP_ID = I.CUSIP_ID
WHERE S.MANAGER_CIK = ? AND S.QUARTER_ID = ?
"""

INSTITUTION_ACTIVITY = """
SELECT
    X.ACTION AS action,
    COUNT(*) AS position_count,
    SUM(COALESCE(X.CURRENT_VALUE_USD, X.PRIOR_VALUE_USD, 0)) AS position_value_usd,
    SUM(COALESCE(X.AMOUNT_CHANGE, 0)) AS amount_change,
    SUM(COALESCE(X.VALUE_CHANGE_USD, 0)) AS value_change_usd
FROM CIK_INSTRUMENT_CHANGE X
JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
WHERE R.MANAGER_CIK = ? AND X.TO_QUARTER_ID = ?
GROUP BY X.ACTION
ORDER BY X.ACTION
"""

INSTITUTION_ALLOCATION = """
SELECT
    T.SECURITY_TYPE_CODE AS security_type,
    SUM(P.VALUE_USD) AS value_usd,
    COUNT(*) AS instrument_count
FROM CIK_INSTRUMENT_QUARTER P
JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
WHERE R.MANAGER_CIK = ? AND P.QUARTER_ID = ?
GROUP BY T.SECURITY_TYPE_CODE
ORDER BY value_usd DESC
"""

INSTITUTION_HISTORY = """
WITH A AS (
    SELECT
        R.MANAGER_CIK,
        X.TO_QUARTER_ID AS QUARTER_ID,
        COUNT(*) FILTER (WHERE X.ACTION = 'NEW') AS new_count,
        COUNT(*) FILTER (WHERE X.ACTION = 'EXITED') AS exited_count,
        SUM(CASE WHEN X.IS_COMPARABLE = 1
            THEN ABS(COALESCE(X.VALUE_CHANGE_USD, 0)) ELSE 0 END)
            AS gross_value_change_usd,
        SUM(CASE WHEN X.IS_COMPARABLE = 1
            THEN COALESCE(X.VALUE_CHANGE_USD, 0) ELSE 0 END)
            AS net_value_change_usd
    FROM CIK_INSTRUMENT_CHANGE X
    JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
    WHERE R.MANAGER_CIK = ?
    GROUP BY R.MANAGER_CIK, X.TO_QUARTER_ID
)
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    S.PORTFOLIO_VALUE_USD AS portfolio_value_usd,
    S.CUSIP_COUNT AS holding_count,
    S.TOP_10_WEIGHT AS top_10_weight,
    S.LARGEST_POSITION_WEIGHT AS largest_position_weight,
    CASE WHEN S.INSTRUMENT_COUNT = 0 THEN NULL
        ELSE 1.0 * S.PORTFOLIO_VALUE_USD / S.INSTRUMENT_COUNT END
        AS average_position_value_usd,
    COALESCE(A.new_count, 0) AS new_count,
    COALESCE(A.exited_count, 0) AS exited_count,
    COALESCE(A.net_value_change_usd, 0) AS net_value_change_usd,
    CASE WHEN S.PORTFOLIO_VALUE_USD = 0 THEN NULL
        ELSE 0.5 * COALESCE(A.gross_value_change_usd, 0)
            / S.PORTFOLIO_VALUE_USD END AS turnover_rate
FROM CIK_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN A USING (MANAGER_CIK, QUARTER_ID)
WHERE S.MANAGER_CIK = ?
ORDER BY S.QUARTER_ID
"""

INSTITUTION_HOLDINGS = """
WITH HOLDING AS (
    SELECT
        R.CIK_INSTRUMENT_ID,
        R.INSTRUMENT_ID,
        P.VALUE_USD AS MARKET_VALUE_USD,
        P.REPORTED_AMOUNT,
        P.AMOUNT_TYPE,
        P.PORTFOLIO_WEIGHT,
        COALESCE(X.ACTION, 'UNCHANGED') AS ACTION,
        X.AMOUNT_CHANGE,
        X.AMOUNT_CHANGE_PERCENT,
        X.VALUE_CHANGE_USD,
        X.IS_COMPARABLE
    FROM CIK_INSTRUMENT_QUARTER P
    JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
    LEFT JOIN CIK_INSTRUMENT_CHANGE X
      ON X.CIK_INSTRUMENT_ID = P.CIK_INSTRUMENT_ID
     AND X.TO_QUARTER_ID = P.QUARTER_ID
    WHERE R.MANAGER_CIK = ? AND P.QUARTER_ID = ?

    UNION ALL

    SELECT
        R.CIK_INSTRUMENT_ID,
        R.INSTRUMENT_ID,
        X.PRIOR_VALUE_USD,
        X.PRIOR_REPORTED_AMOUNT,
        I.AMOUNT_TYPE,
        NULL,
        X.ACTION,
        X.AMOUNT_CHANGE,
        X.AMOUNT_CHANGE_PERCENT,
        X.VALUE_CHANGE_USD,
        X.IS_COMPARABLE
    FROM CIK_INSTRUMENT_CHANGE X
    JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
    JOIN INSTRUMENT I USING (INSTRUMENT_ID)
    LEFT JOIN CIK_INSTRUMENT_QUARTER P
      ON P.CIK_INSTRUMENT_ID = X.CIK_INSTRUMENT_ID
     AND P.QUARTER_ID = X.TO_QUARTER_ID
    WHERE R.MANAGER_CIK = ?
      AND X.TO_QUARTER_ID = ?
      AND P.CIK_INSTRUMENT_QUARTER_ID IS NULL
)
SELECT
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    T.SECURITY_TYPE_CODE AS security_type,
    I.OPTION_TYPE AS option_type,
    H.MARKET_VALUE_USD AS market_value_usd,
    H.REPORTED_AMOUNT AS reported_amount,
    H.AMOUNT_TYPE AS amount_type,
    H.PORTFOLIO_WEIGHT AS portfolio_weight,
    H.ACTION AS action,
    H.AMOUNT_CHANGE AS amount_change,
    H.AMOUNT_CHANGE_PERCENT AS amount_change_percent,
    H.VALUE_CHANGE_USD AS value_change_usd,
    H.IS_COMPARABLE AS is_comparable
FROM HOLDING H
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
WHERE (? = '' OR H.ACTION = ?)
  AND (
      ? = ''
      OR V.CUSIP LIKE '%' || ? || '%'
      OR V.CURRENT_NAMEOFISSUER LIKE '%' || ? || '%'
  )
ORDER BY {order_expression} DESC
LIMIT ? OFFSET ?
"""

SECURITIES = """
WITH ACTIVITY AS (
    SELECT
        I.CUSIP_ID,
        COUNT(*) FILTER (WHERE X.ACTION = 'NEW') AS new_investor_count,
        COUNT(*) FILTER (WHERE X.ACTION = 'EXITED') AS exited_investor_count,
        COUNT(*) FILTER (WHERE X.ACTION = 'ADDED') AS added_holder_count,
        COUNT(*) FILTER (WHERE X.ACTION = 'REDUCED') AS reduced_holder_count,
        SUM(CASE WHEN X.IS_COMPARABLE = 1
            THEN COALESCE(X.VALUE_CHANGE_USD, 0) ELSE 0 END)
            AS net_value_change_usd
    FROM CIK_INSTRUMENT_CHANGE X
    JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
    JOIN INSTRUMENT I USING (INSTRUMENT_ID)
    WHERE X.TO_QUARTER_ID = ?
    GROUP BY I.CUSIP_ID
)
SELECT
    S.CUSIP_ID AS cusip_id,
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    T.SECURITY_TYPE_CODE AS security_type,
    Q.QUARTER_LABEL AS quarter_label,
    S.MANAGER_COUNT AS institution_count,
    S.TOTAL_VALUE_USD AS institutional_value_usd,
    S.COMMON_STOCK_VALUE_USD AS common_stock_value_usd,
    S.CALL_VALUE_USD AS call_value_usd,
    S.PUT_VALUE_USD AS put_value_usd,
    S.MANAGER_CONCENTRATION_HHI AS concentration_hhi,
    COALESCE(A.new_investor_count, 0) AS new_investor_count,
    COALESCE(A.exited_investor_count, 0) AS exited_investor_count,
    COALESCE(A.added_holder_count, 0) AS added_holder_count,
    COALESCE(A.reduced_holder_count, 0) AS reduced_holder_count,
    COALESCE(A.net_value_change_usd, 0) AS net_value_change_usd
FROM CUSIP_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
LEFT JOIN CUSIP_CLASSIFICATION C USING (CUSIP_ID)
LEFT JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
LEFT JOIN ACTIVITY A USING (CUSIP_ID)
WHERE S.QUARTER_ID = ?
  AND (
      ? = ''
      OR V.CUSIP LIKE '%' || ? || '%'
      OR V.CURRENT_NAMEOFISSUER LIKE '%' || ? || '%'
  )
  {filter_clauses}
ORDER BY {order_expression} {order_direction}, issuer
LIMIT ? OFFSET ?
"""

SECURITY_IDENTITY = """
SELECT
    V.CUSIP_ID AS cusip_id,
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    V.CURRENT_FIGI AS figi,
    T.SECURITY_TYPE_CODE AS security_type,
    C.CLASSIFICATION_METHOD AS classification_method,
    C.CLASSIFICATION_CONFIDENCE AS classification_confidence,
    MIN(Q.QUARTER_LABEL) AS first_reportable_quarter,
    MAX(Q.QUARTER_LABEL) AS latest_reportable_quarter
FROM CUSIP_CURRENT_VARIANT V
LEFT JOIN CUSIP_CLASSIFICATION C USING (CUSIP_ID)
LEFT JOIN SECURITY_TYPE T USING (SECURITY_TYPE_ID)
LEFT JOIN CUSIP_QUARTER_SUMMARY S USING (CUSIP_ID)
LEFT JOIN QUARTER Q USING (QUARTER_ID)
WHERE V.CUSIP = ?
GROUP BY V.CUSIP_ID
"""

SECURITY_SNAPSHOT = """
SELECT
    S.*,
    Q.QUARTER_LABEL AS quarter_label,
    CASE WHEN S.MANAGER_COUNT = 0 THEN NULL
        ELSE 1.0 * S.TOTAL_VALUE_USD / S.MANAGER_COUNT END
        AS average_position_value_usd,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        S.LARGEST_MANAGER_CIK) AS largest_holder_name
FROM CUSIP_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN CIK C ON C.CIK = S.LARGEST_MANAGER_CIK
JOIN CUSIP D USING (CUSIP_ID)
WHERE D.CUSIP = ? AND S.QUARTER_ID = ?
"""

SECURITY_ACTIVITY = """
SELECT
    X.ACTION AS action,
    COUNT(DISTINCT R.MANAGER_CIK) AS institution_count,
    SUM(COALESCE(X.VALUE_CHANGE_USD, 0)) AS value_change_usd
FROM CIK_INSTRUMENT_CHANGE X
JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN CUSIP D USING (CUSIP_ID)
WHERE D.CUSIP = ? AND X.TO_QUARTER_ID = ?
GROUP BY X.ACTION
ORDER BY X.ACTION
"""

SECURITY_HISTORY = """
WITH A AS (
    SELECT
        X.TO_QUARTER_ID AS QUARTER_ID,
        COUNT(DISTINCT CASE WHEN X.ACTION = 'NEW'
            THEN R.MANAGER_CIK END) AS new_investor_count,
        COUNT(DISTINCT CASE WHEN X.ACTION = 'EXITED'
            THEN R.MANAGER_CIK END) AS exited_investor_count,
        SUM(CASE WHEN X.IS_COMPARABLE = 1
            THEN COALESCE(X.VALUE_CHANGE_USD, 0) ELSE 0 END)
            AS net_value_change_usd
    FROM CIK_INSTRUMENT_CHANGE X
    JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
    JOIN INSTRUMENT I USING (INSTRUMENT_ID)
    JOIN CUSIP D USING (CUSIP_ID)
    WHERE D.CUSIP = ?
    GROUP BY X.TO_QUARTER_ID
)
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    S.MANAGER_COUNT AS institution_count,
    S.TOTAL_VALUE_USD AS institutional_value_usd,
    S.MANAGER_CONCENTRATION_HHI AS concentration_hhi,
    CASE WHEN S.MANAGER_COUNT = 0 THEN NULL
        ELSE 1.0 * S.TOTAL_VALUE_USD / S.MANAGER_COUNT END
        AS average_position_value_usd,
    COALESCE(A.new_investor_count, 0) AS new_investor_count,
    COALESCE(A.exited_investor_count, 0) AS exited_investor_count,
    COALESCE(A.net_value_change_usd, 0) AS net_value_change_usd
FROM CUSIP_QUARTER_SUMMARY S
JOIN QUARTER Q USING (QUARTER_ID)
JOIN CUSIP D USING (CUSIP_ID)
LEFT JOIN A USING (QUARTER_ID)
WHERE D.CUSIP = ?
ORDER BY S.QUARTER_ID
"""

SECURITY_HOLDERS = """
WITH SECURITY_POSITION AS (
    SELECT
        R.MANAGER_CIK,
        P.CIK_INSTRUMENT_ID,
        P.VALUE_USD AS MARKET_VALUE_USD,
        P.REPORTED_AMOUNT,
        P.PORTFOLIO_WEIGHT,
        COALESCE(X.ACTION, 'UNCHANGED') AS ACTION,
        X.AMOUNT_CHANGE,
        X.VALUE_CHANGE_USD
    FROM CIK_INSTRUMENT_QUARTER P
    JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
    JOIN INSTRUMENT I USING (INSTRUMENT_ID)
    JOIN CUSIP D USING (CUSIP_ID)
    LEFT JOIN CIK_INSTRUMENT_CHANGE X
      ON X.CIK_INSTRUMENT_ID = P.CIK_INSTRUMENT_ID
     AND X.TO_QUARTER_ID = P.QUARTER_ID
    WHERE D.CUSIP = ? AND P.QUARTER_ID = ?

    UNION ALL

    SELECT
        R.MANAGER_CIK,
        X.CIK_INSTRUMENT_ID,
        X.PRIOR_VALUE_USD,
        X.PRIOR_REPORTED_AMOUNT,
        NULL,
        X.ACTION,
        X.AMOUNT_CHANGE,
        X.VALUE_CHANGE_USD
    FROM CIK_INSTRUMENT_CHANGE X
    JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
    JOIN INSTRUMENT I USING (INSTRUMENT_ID)
    JOIN CUSIP D USING (CUSIP_ID)
    LEFT JOIN CIK_INSTRUMENT_QUARTER P
      ON P.CIK_INSTRUMENT_ID = X.CIK_INSTRUMENT_ID
     AND P.QUARTER_ID = X.TO_QUARTER_ID
    WHERE D.CUSIP = ?
      AND X.TO_QUARTER_ID = ?
      AND P.CIK_INSTRUMENT_QUARTER_ID IS NULL
),
HOLDER AS (
    SELECT
        S.MANAGER_CIK,
        SUM(S.MARKET_VALUE_USD) AS MARKET_VALUE_USD,
        SUM(S.REPORTED_AMOUNT) AS REPORTED_AMOUNT,
        MAX(S.PORTFOLIO_WEIGHT) AS PORTFOLIO_WEIGHT,
        CASE
            WHEN SUM(S.ACTION = 'UNKNOWN') > 0 THEN 'UNKNOWN'
            WHEN SUM(S.ACTION = 'NEW') > 0 THEN 'NEW'
            WHEN SUM(S.ACTION = 'ADDED') > 0 THEN 'ADDED'
            WHEN SUM(S.ACTION = 'REDUCED') > 0 THEN 'REDUCED'
            WHEN SUM(S.ACTION = 'EXITED') > 0 THEN 'EXITED'
            ELSE 'UNCHANGED'
        END AS ACTION,
        SUM(COALESCE(S.AMOUNT_CHANGE, 0)) AS AMOUNT_CHANGE,
        SUM(COALESCE(S.VALUE_CHANGE_USD, 0)) AS VALUE_CHANGE_USD
    FROM SECURITY_POSITION S
    GROUP BY S.MANAGER_CIK
)
SELECT
    H.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        H.MANAGER_CIK) AS institution_name,
    H.MARKET_VALUE_USD AS market_value_usd,
    H.REPORTED_AMOUNT AS reported_amount,
    H.PORTFOLIO_WEIGHT AS portfolio_weight,
    H.ACTION AS action,
    H.AMOUNT_CHANGE AS amount_change,
    H.VALUE_CHANGE_USD AS value_change_usd
FROM HOLDER H
LEFT JOIN CIK C ON C.CIK = H.MANAGER_CIK
WHERE (? = '' OR H.ACTION = ?)
  AND (
      ? = ''
      OR H.MANAGER_CIK LIKE '%' || ? || '%'
      OR C.MANAGER_NAME LIKE '%' || ? || '%'
      OR C.SEC_COMPANY_NAME LIKE '%' || ? || '%'
  )
ORDER BY {order_expression} DESC
LIMIT ? OFFSET ?
"""

RELATIONSHIP_IDENTITY = """
SELECT
    R.MANAGER_CIK AS cik,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        R.MANAGER_CIK) AS institution_name,
    V.CUSIP AS cusip,
    V.CURRENT_NAMEOFISSUER AS issuer,
    V.CURRENT_TITLEOFCLASS AS title_of_class,
    MIN(Q.QUARTER_LABEL) AS first_purchased,
    MAX(Q.QUARTER_LABEL) AS latest_quarter
FROM CIK_INSTRUMENT R
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN CUSIP_CURRENT_VARIANT V USING (CUSIP_ID)
LEFT JOIN CIK C ON C.CIK = R.MANAGER_CIK
JOIN CIK_INSTRUMENT_QUARTER P USING (CIK_INSTRUMENT_ID)
JOIN QUARTER Q USING (QUARTER_ID)
WHERE R.MANAGER_CIK = ? AND V.CUSIP = ?
GROUP BY R.MANAGER_CIK, V.CUSIP
"""

RELATIONSHIP_HISTORY = """
SELECT
    Q.QUARTER_ID AS quarter_id,
    Q.QUARTER_LABEL AS quarter_label,
    SUM(P.VALUE_USD) AS market_value_usd,
    SUM(P.REPORTED_AMOUNT) AS reported_amount,
    MAX(P.PORTFOLIO_WEIGHT) AS portfolio_weight,
    COALESCE(MAX(X.ACTION), 'UNCHANGED') AS action,
    SUM(COALESCE(X.AMOUNT_CHANGE, 0)) AS amount_change,
    MAX(X.AMOUNT_CHANGE_PERCENT) AS amount_change_percent,
    SUM(COALESCE(X.VALUE_CHANGE_USD, 0)) AS value_change_usd
FROM CIK_INSTRUMENT_QUARTER P
JOIN CIK_INSTRUMENT R USING (CIK_INSTRUMENT_ID)
JOIN INSTRUMENT I USING (INSTRUMENT_ID)
JOIN CUSIP D USING (CUSIP_ID)
JOIN QUARTER Q USING (QUARTER_ID)
LEFT JOIN CIK_INSTRUMENT_CHANGE X
  ON X.CIK_INSTRUMENT_ID = P.CIK_INSTRUMENT_ID
 AND X.TO_QUARTER_ID = P.QUARTER_ID
WHERE R.MANAGER_CIK = ? AND D.CUSIP = ?
GROUP BY P.QUARTER_ID
ORDER BY P.QUARTER_ID
"""

GLOBAL_SEARCH = """
SELECT 'institution' AS result_type, C.CIK AS result_id,
    COALESCE(NULLIF(C.MANAGER_NAME, ''), NULLIF(C.SEC_COMPANY_NAME, ''),
        C.CIK) AS label,
    'CIK ' || C.CIK AS detail
FROM CIK C
WHERE C.CIK LIKE ? OR C.MANAGER_NAME LIKE ? OR C.SEC_COMPANY_NAME LIKE ?
UNION ALL
SELECT 'security', V.CUSIP, V.CURRENT_NAMEOFISSUER,
    V.CUSIP || ' · ' || COALESCE(V.CURRENT_TITLEOFCLASS, 'Unclassified')
FROM CUSIP_CURRENT_VARIANT V
WHERE V.CUSIP LIKE ? OR V.CURRENT_NAMEOFISSUER LIKE ?
LIMIT 12
"""
